JavaScript/JavaScriptSDK.Tests/CheckinTests/Context/Session.tests.ts
JavaScript/JavaScriptSDK.Tests/CheckinTests/Initialization.tests.ts
JavaScript/JavaScriptSDK.Tests/CheckinTests/Sender.tests.ts
JavaScript/JavaScriptSDK.Tests/CheckinTests/Serializer.tests.ts
JavaScript/JavaScriptSDK.Tests/CheckinTests/Telemetry/DataSanitizer.tests.ts
JavaScript/JavaScriptSDK.Tests/CheckinTests/TelemetryContext.tests.ts
JavaScript/JavaScriptSDK.Tests/CheckinTests/Util.tests.ts
JavaScript/JavaScriptSDK.Tests/CheckinTests/appInsights.tests.ts
JavaScript/JavaScriptSDK.Tests/JavaScriptSDK.Tests.csproj
JavaScript/JavaScriptSDK.Tests/Selenium/Tests.cs
JavaScript/JavaScriptSDK/Context/Internal.ts
JavaScript/JavaScriptSDK/Context/Session.ts
JavaScript/JavaScriptSDK/Initialization.ts
JavaScript/JavaScriptSDK/JavaScriptSDK.csproj
JavaScript/JavaScriptSDK/Sender.ts
JavaScript/JavaScriptSDK/Telemetry/Common/DataSanitizer.ts
JavaScript/JavaScriptSDK/Util.ts
JavaScript/JavaScriptSDK/appInsights.ts
JavaScript/JavaScriptSDK/web.Debug.config
JavaScript/JavaScriptSDK/web.Release.config
JavaScript/JavaScriptSDK/web.config
JavaScript/Microsoft.ApplicationInsights.JavaScript.sln

Bringing AI-JS version on GitHub up to date with the latest changes in AppDataCollection-JS

Bringing AI-JS version on GitHub up to date with the latest changes in AppDataCollection-JS

---

JavaScript/JavaScriptSDK.Tests/JavaScriptSDK.Tests.csproj
JavaScript/JavaScriptSDK.Tests/Selenium/Tests.cs
README.md

Some tweaks to tests and proj as part of the work to create automatic builds for master branch. This is mostly invisible to internal contributor yet as we are not enabling automatic builds for feature branches yet.
Another part of work was setting up performance tests to build up a perf history file with each commit to master branch. The idea is to make this perf info public and update it for each release.

Auto build and perf tests csv

---

JavaScript/JavaScriptSDK.Tests/CheckinTests/Logging.tests.ts
JavaScript/JavaScriptSDK.Tests/CheckinTests/Sender.tests.ts
JavaScript/JavaScriptSDK.Tests/CheckinTests/Telemetry/PageViewPerformance.tests.ts
JavaScript/JavaScriptSDK.Tests/CheckinTests/appInsights.tests.ts
JavaScript/JavaScriptSDK/Initialization.ts
JavaScript/JavaScriptSDK/Logging.ts
JavaScript/JavaScriptSDK/TelemetryContext.ts
JavaScript/JavaScriptSDK/appInsights.ts

Note: Please ignore the master commit. Did a master push before by mistake. I have reverted the changes.
Changes -
Add the logic for throttling of internal events
Add the logic to reset this throttle on page views.

Initial changes for simple throttling of internal events

---

JavaScript/JavaScriptSDK.Tests/E2ETests/snippet.tests.ts
JavaScript/JavaScriptSDK.Tests/Performance/pageLoad.perftests.ts
JavaScript/JavaScriptSDK.Tests/Selenium/PerfTests.html
JavaScript/JavaScriptSDK.Tests/Selenium/Tests.cs
JavaScript/JavaScriptSDK.Tests/Selenium/Tests.html
JavaScript/JavaScriptSDK.Tests/TestFramework/PerformanceTestHelper.ts
JavaScript/JavaScriptSDK.Tests/TestFramework/TestClass.ts

1) switched perf tests to new quinit
2) they now take too much time (minutes) to execute - disabling them as CI tests

Fixing perf tests

---

JavaScript/Microsoft.ApplicationInsights.JavaScript.sln
JavaScript/NuGet.JavaScript/NuGet.JavaScript.csproj
JavaScript/NuGet.JavaScript/Package.nuspec
JavaScript/NuGet.TypeScript/NuGet.TypeScript.csproj
JavaScript/NuGet.TypeScript/Package.nuspec
Package.targets

Changing build, build def to ensure Nuget files are copied to output, fixing nuget license and project URLs

Changing build, build def to ensure Nuget files are copied to output, fixing nuget license and project URLs

---

JavaScript/.gitignore

Adding JS ignore to the gitignore file

---

JavaScript/JavaScriptSDK.Tests/CheckinTests/Initialization.tests.ts
JavaScript/JavaScriptSDK.Tests/CheckinTests/Sender.tests.ts
JavaScript/JavaScriptSDK.Tests/CheckinTests/Util.tests.ts
JavaScript/JavaScriptSDK/Init.ts
JavaScript/JavaScriptSDK/Initialization.ts
JavaScript/JavaScriptSDK/Sender.ts
JavaScript/JavaScriptSDK/Util.ts

- Hooks up with the onbeforeunload event and attaches a callback that will try to flush all pending events
- This callback will handle sending of these events asynchronously for now

Initial changes for supporting flushing of events on before page unload

---

JavaScript/JavaScriptSDK.Tests/CheckinTests/appInsights.tests.ts
JavaScript/JavaScriptSDK.Tests/E2ETests/PublicApiTests.ts
JavaScript/JavaScriptSDK/Util.ts
JavaScript/JavaScriptSDK/appInsights.ts

1) Removed ai.0.js from Script error's stack trace
2) Added URL custom property showing document.url to make the error more friendly

Scripterror

---

JavaScript/JavaScriptSDK/Init.ts
JavaScript/JavaScriptSDK/Util.ts

- try-catch for localStorage
- try-catch for the initialize entry point
@MaxShehovtsov @olegsych @OsvaldoRosado

Adding try catch for local storage and initialize entry point

---

README.md

Adding link to ainow to help customers try Application Insights with JS SDK without having to create an Azure account

README.md - add information about AINow

---

JavaScript/JavaScriptSDK/appInsights.ts

Page view duration now should be equal to client perf.total

synchronizing page view duration with client perf total

---

JavaScript/JavaScriptSDK.Tests/CheckinTests/Telemetry/RemoteDependency.tests.ts
JavaScript/JavaScriptSDK.Tests/CheckinTests/ajax.tests.ts
JavaScript/JavaScriptSDK.Tests/CheckinTests/appInsights.tests.ts
JavaScript/JavaScriptSDK.Tests/E2ETests/autoCollection.tests.ts
JavaScript/JavaScriptSDK.Tests/E2ETests/autoCollectionTemplates/ajax.html
JavaScript/JavaScriptSDK/Telemetry/RemoteDependencyData.ts
JavaScript/JavaScriptSDK/ajax/ajax.ts
JavaScript/JavaScriptSDK/ajax/ajaxRecord.ts
JavaScript/JavaScriptSDK/appInsights.ts

Addressed feedback from here - https://github.com/Microsoft/ApplicationInsights-JS/issues/84

Ajax feedback

---

JavaScript/JavaScriptSDK.Tests/CheckinTests/Context/Session.tests.ts
JavaScript/JavaScriptSDK.Tests/CheckinTests/Context/User.tests.ts
JavaScript/JavaScriptSDK.Tests/CheckinTests/TelemetryContext.tests.ts
JavaScript/JavaScriptSDK.Tests/CheckinTests/Util.tests.ts
JavaScript/JavaScriptSDK.Tests/CheckinTests/appInsights.tests.ts
JavaScript/JavaScriptSDK/Context/Device.ts
JavaScript/JavaScriptSDK/Context/Operation.ts
JavaScript/JavaScriptSDK/Context/Session.ts
JavaScript/JavaScriptSDK/Context/User.ts
JavaScript/JavaScriptSDK/TelemetryContext.ts
JavaScript/JavaScriptSDK/Util.ts

Make identifiers shorter and remove some data we collect by default 
[#73](https://github.com/Microsoft/ApplicationInsights-JS/issues/73)

some minimization

---

JavaScript/JavaScriptSDK.Tests/CheckinTests/appInsights.tests.ts
JavaScript/JavaScriptSDK/appInsights.ts

Send the duration between startTrackEvent and stopTrackEvent to the server.

Log duration on stopTrackEvent

---

JavaScript/JavaScriptSDK.Tests/CheckinTests/Initialization.tests.ts
JavaScript/JavaScriptSDK.Tests/CheckinTests/appInsights.tests.ts
JavaScript/JavaScriptSDK.Tests/E2ETests/PostBuild.ps1
JavaScript/JavaScriptSDK/AppInsights.ts
JavaScript/JavaScriptSDK/Initialization.ts

…cking instead of autoCollectAjax
Issue #59

rename config params

---

JavaScript/JavaScriptSDK.Tests/CheckinTests/appInsights.tests.ts
JavaScript/JavaScriptSDK/AppInsights.ts
JavaScript/JavaScriptSDK/JavaScriptSDK.csproj
JavaScript/JavaScriptSDK/Telemetry/PageViewManager.ts

TrackPageView refactoring

---

API-reference.md

Added descriptions for trackPageView duration parameter and overridePageVIew duration configuration

Update documentation to add custom duration

---

JavaScript/JavaScriptSDK/Util.ts
JavaScript/JavaScriptSDK/ajax/ajax.ts
JavaScript/JavaScriptSDK/ajax/ajaxRecord.ts

Made ajax dependencies send url as name

---

JavaScript/JavaScriptSDK.Tests/CheckinTests/TelemetryContext.tests.ts
JavaScript/JavaScriptSDK/TelemetryContext.ts

Don't want an item to be sent? Return false from telemetry initializer and you're all set!

supported filtering out items with telemetry initializers

---

API-reference.md

For bug https://github.com/Microsoft/ApplicationInsights-JS/issues/134

Added documentation for start/stop track page

---

JavaScript/JavaScriptSDK.Tests/CheckinTests/appInsights.tests.ts
JavaScript/JavaScriptSDK/AppInsights.ts
JavaScript/JavaScriptSDK/Telemetry/Event.ts
JavaScript/JavaScriptSDK/Telemetry/Exception.ts
JavaScript/JavaScriptSDK/Telemetry/Metric.ts
JavaScript/JavaScriptSDK/Telemetry/PageView.ts
JavaScript/JavaScriptSDK/Telemetry/PageViewPerformance.ts
JavaScript/JavaScriptSDK/Telemetry/RemoteDependencyData.ts
JavaScript/JavaScriptSDK/Telemetry/SessionTelemetry.ts
JavaScript/JavaScriptSDK/Telemetry/Trace.ts
JavaScript/JavaScriptSDK/TelemetryContext.ts

Microsoft.ApplicationInsights.Event -> Microsoft.ApplicationInsights.iKey.Event
And same for all other types

Add iKey to telemetry name

---

bower.json
package.json

Updated release instructions, so we don't forget to do it before releasing new version

Updating version in package.json and bower.json

---

Global.props

Updating version in global.props

---

Global.props
JavaScript/JavaScriptSDK.Tests/CheckinTests/Context/Session.tests.ts
JavaScript/JavaScriptSDK.Tests/CheckinTests/DataLossAnalyzer.tests.ts
JavaScript/JavaScriptSDK.Tests/CheckinTests/Sender.tests.ts
JavaScript/JavaScriptSDK.Tests/CheckinTests/appInsights.tests.ts
JavaScript/JavaScriptSDK/AppInsights.ts
JavaScript/JavaScriptSDK/DataLossAnalyzer.ts
JavaScript/JavaScriptSDK/Util.ts
bower.json
package.json

Only calling window.localStorage and window.sessionStorage after safe checks

---

JavaScript/JavaScriptSDK.Tests/CheckinTests/Telemetry/RemoteDependency.tests.ts
JavaScript/JavaScriptSDK/Telemetry/Common/DataSanitizer.ts
JavaScript/JavaScriptSDK/Telemetry/RemoteDependencyData.ts

Truncating CommandName to 2048 characters

---

changeSdkVersion.ps1
uploadFilesToAzureStorage.ps1

Two first steps of the release script
- Update version number
- Upload files to the Azure Storage

Release script

---

JavaScript/JavaScriptSDK.Tests/CheckinTests/Logging.tests.ts
JavaScript/JavaScriptSDK.Tests/CheckinTests/Sender.tests.ts
JavaScript/JavaScriptSDK.Tests/CheckinTests/Telemetry/PageViewPerformance.tests.ts
JavaScript/JavaScriptSDK/Logging.ts

Show AI internal traces in console only when verboseLogging is enabled

---

API-reference.md
JavaScript/JavaScriptSDK.Tests/CheckinTests/Telemetry/Exception.tests.ts
JavaScript/JavaScriptSDK.Tests/CheckinTests/appInsights.tests.ts
JavaScript/JavaScriptSDK/AppInsights.ts
JavaScript/JavaScriptSDK/Telemetry/Exception.ts

Allow passing severityLevel in trackException

---

JavaScript/JavaScriptSDK.Tests/CheckinTests/Sender.tests.ts
JavaScript/JavaScriptSDK/AppInsights.ts
JavaScript/JavaScriptSDK/SendBuffer.ts
JavaScript/JavaScriptSDK/Sender.ts

Session storage bug fixes

---

JavaScript/JavaScriptSDK.Tests/CheckinTests/SendBuffer.tests.ts
JavaScript/JavaScriptSDK.Tests/CheckinTests/Sender.tests.ts
JavaScript/JavaScriptSDK/DataLossAnalyzer.ts
JavaScript/JavaScriptSDK/SendBuffer.ts
JavaScript/JavaScriptSDK/Sender.ts

* Disable DataLossAnalyzer for XDomainRequest 
* Sender calls buffer.GetItems only once

Disable DataLossAnalyzer for XDomainRequest

---

JavaScript/JavaScriptSDK.Tests/CheckinTests/TelemetryContext.tests.ts
JavaScript/JavaScriptSDK/Context/Internal.ts

Make sdk version prefix lowercase

---

JavaScript/JavaScriptSDK.Module/AppInsightsModule.js
JavaScript/JavaScriptSDK.Module/AppInsightsModule.ts

Updating default setting to aiConfig.url to not hardcode http endpoint

---

JavaScript/JavaScriptSDK.Interfaces/ITelemetryContext.ts
JavaScript/JavaScriptSDK.Interfaces/JavaScriptSDK.Interfaces.csproj
JavaScript/JavaScriptSDK.Interfaces/Telemetry/IEnvelope.ts
JavaScript/JavaScriptSDK.Interfaces/Telemetry/ISerializable.ts
JavaScript/JavaScriptSDK/Context/Sample.ts
JavaScript/JavaScriptSDK/SamplingScoreGenerator.ts
JavaScript/JavaScriptSDK/Sender.ts
JavaScript/JavaScriptSDK/Serializer.ts
JavaScript/JavaScriptSDK/Telemetry/Common/Envelope.ts
JavaScript/JavaScriptSDK/Telemetry/RemoteDependencyData.ts
JavaScript/JavaScriptSDK/TelemetryContext.ts

More fixes and clean up for #230

Add IEnvelope and ISerializable interfaces

---

JavaScript/JavaScriptSDK.Tests/DefinitionTypes/applicationinsights-js-tests.ts
JavaScript/JavaScriptSDK.Tests/JavaScriptSDK.Tests.csproj

The file won't compile if we make breaking changes to interfaces or public signatures.

Test for d.ts files hosted in DefinitelyTyped repo

---

JavaScript/JavaScriptSDK/AppInsights.ts
JavaScript/JavaScriptSDK/DataLossAnalyzer.ts

* Disable session storage buffer experiment
* Fix Data loss analyzer bug

Disable experiment

---

README.md

making the snippet being javascript compatible (was typescript)

fix readme/js snippet

---

JavaScript/JavaScriptSDK/Initialization.ts

Ship session storage buffer

---

Global.props
JavaScript/JavaScriptSDK/AppInsights.ts
bower.json
package.json

Release:
* #254 - Ship session storage buffer
* #235 - Add IEnvelope and ISerializable interfaces
* bug fixes

version update 0.22.19 -> 0.23.0

---

Global.props
JavaScript/JavaScriptSDK/AppInsights.ts
bower.json
package.json

Release version 1.0.0 :smile: :cocktail: :fireworks:

version update 0.23.2 -> 1.0.0

---

Global.props
JavaScript/JavaScriptSDK/AppInsights.ts
bower.json
package.json

Switching back to 0.23.4. We are experiencing some internal back-end issue with processing data marked as v1.0.0,.

version update 1.0.0 -> 0.23.4

---

JavaScript/JavaScriptSDK.Interfaces/IConfig.ts
JavaScript/JavaScriptSDK.Tests/CheckinTests/Context/Session.tests.ts
JavaScript/JavaScriptSDK.Tests/CheckinTests/Context/User.tests.ts
JavaScript/JavaScriptSDK.Tests/CheckinTests/SendBuffer.tests.ts
JavaScript/JavaScriptSDK.Tests/CheckinTests/Sender.tests.ts
JavaScript/JavaScriptSDK.Tests/CheckinTests/TelemetryContext.tests.ts
JavaScript/JavaScriptSDK.Tests/E2ETests/DisableTelemetryTests.ts
JavaScript/JavaScriptSDK/AppInsights.ts
JavaScript/JavaScriptSDK/Initialization.ts
JavaScript/JavaScriptSDK/Sender.ts

Enable retry handler for 10% of users.

Enable retry handler

---

JavaScript/JavaScriptSDK.Interfaces/IConfig.ts
JavaScript/JavaScriptSDK/AppInsights.ts
JavaScript/JavaScriptSDK/Initialization.ts
JavaScript/JavaScriptSDK/JavaScriptSDK.csproj
JavaScript/JavaScriptSDK/Telemetry/PerformanceAnalyzer.ts

Enable experiment to collect performance number for Application Insights endpoints.

AppInsights endpoint performance analyzer

---

JavaScript/JavaScriptSDK/snippet.js
README.md

Fixes issue #293.
I ran `powershell "& .\RunTestsInBrowser.ps1"` and it's all green. I'd like to add a test for this but the current snippet tests seem to hardcode the config so I couldn't think of a great way to simulate the ai.js script not properly loading to test the lazy methods are properly set up. I'm open to suggestion :)

Add missing lazy methods

---

JavaScript/JavaScriptSDK.Tests/E2ETests/E2E.ValidateApiTests.htm
JavaScript/JavaScriptSDK.Tests/E2ETests/ValidateApiTests.ts
JavaScript/JavaScriptSDK.Tests/JavaScriptSDK.Tests.csproj
JavaScript/JavaScriptSDK.Tests/Selenium/Tests.cs

Initial set of /v2/validate api tests

---

API-reference.md
JavaScript/JavaScriptSDK/AppInsights.ts
JavaScript/JavaScriptSDK/Initialization.ts

* finish the experiment
* enable retry handler by default

Ship retry handler

---

JavaScript/JavaScriptSDK.Interfaces/Contracts/Generated/RemoteDependencyData.ts
JavaScript/JavaScriptSDK.Tests/CheckinTests/appInsights.tests.ts
JavaScript/JavaScriptSDK.Tests/DefinitionTypes/applicationinsights-js-tests.ts
JavaScript/JavaScriptSDK/AppInsights.ts
JavaScript/JavaScriptSDK/Telemetry/RemoteDependencyData.ts

Add support for tracking properties and measurements in trackDependency

---

JavaScript/JavaScriptSDK.Tests/CheckinTests/appInsights.tests.ts
JavaScript/JavaScriptSDK/Initialization.ts
JavaScript/JavaScriptSDK/ajax/ajax.ts

Enable correlation headers

---

API-reference.md
JavaScript/JavaScriptSDK.Interfaces/IConfig.ts
JavaScript/JavaScriptSDK.Tests/CheckinTests/Util.tests.ts
JavaScript/JavaScriptSDK/AppInsights.ts
JavaScript/JavaScriptSDK/Initialization.ts
JavaScript/JavaScriptSDK/Util.ts

Expose an option to disable cookies

---

JavaScript/JavaScriptSDK/Util.ts

* Don't log session storage read/write/remove errors 
* Disable local/session storage if there was an exception associated with them.

Don't log session storage errors

---

JavaScript/JavaScriptSDK/Initialization.ts

Set maxBatchSize limit to 100kb. See [config](https://github.com/Microsoft/ApplicationInsights-JS/blob/UpdateMaxBatchSize/API-reference.md#config) documentation.

Update maxBatchSize to match the documentation

---

JavaScript/JavaScriptSDK.Tests/CheckinTests/Context/Session.tests.ts
JavaScript/JavaScriptSDK/Context/Session.ts
JavaScript/JavaScriptSDK/ajax/ajaxRecord.ts
JavaScript/JavaScriptSDK/ajax/ajaxUtils.ts

Use performance.now in session class

---

JavaScript/JavaScriptSDK/SendBuffer.ts
JavaScript/JavaScriptSDK/Sender.ts

Report those errors only in debug mode.

Don't log buffer errors

---

JavaScript/.npmignore

This file is useful if someone wants to use application insights from a separate file instead of using inline JavaScript (For performance and security reasons) using a Gulp pipeline.

Add snippet.js to NPM package

---

JavaScript/JavaScriptSDK.Interfaces/IAppInsights.ts
JavaScript/JavaScriptSDK/Telemetry/Event.ts
JavaScript/JavaScriptSDK/Telemetry/Exception.ts
JavaScript/JavaScriptSDK/Telemetry/Metric.ts
JavaScript/JavaScriptSDK/Telemetry/Trace.ts

Fixes related to https://github.com/DefinitelyTyped/DefinitelyTyped/pull/14302

Fix TSLint errors

---

JavaScript/JavaScriptSDK.Tests/CheckinTests/appInsights.tests.ts
JavaScript/JavaScriptSDK/AppInsights.ts
JavaScript/JavaScriptSDK/ajax/ajax.ts

Add correlation headers for request within the same domain

---

JavaScript/JavaScriptSDK/Initialization.ts

Reenable correlation headers

---

API-reference.md
JavaScript/JavaScriptSDK/AppInsights.ts

Update track* documentation

---

API-reference.md
JavaScript/JavaScriptSDK.Interfaces/IConfig.ts
JavaScript/JavaScriptSDK.Tests/CheckinTests/Context/Session.tests.ts
JavaScript/JavaScriptSDK.Tests/CheckinTests/Context/User.tests.ts
JavaScript/JavaScriptSDK.Tests/CheckinTests/TelemetryContext.tests.ts
JavaScript/JavaScriptSDK.Tests/E2ETests/snippet.tests.ts
JavaScript/JavaScriptSDK/AppInsights.ts
JavaScript/JavaScriptSDK/Context/Internal.ts
JavaScript/JavaScriptSDK/Init.ts
JavaScript/JavaScriptSDK/Initialization.ts
JavaScript/JavaScriptSDK/TelemetryContext.ts
JavaScript/JavaScriptSDK/snippet.js

Fixes #463. I also remove 'snippetVersion' which is not used anymore.

Allow setting sdk extension name

---

JavaScript/JavaScriptSDK.Tests/CheckinTests/appInsights.tests.ts
JavaScript/JavaScriptSDK/ajax/ajax.ts

CORS check should include a port number

---

JavaScript/JavaScriptSDK.Tests/E2ETests/PostBuild.ps1
JavaScript/JavaScriptSDK.Tests/E2ETests/snippet.tests.ts
JavaScript/JavaScriptSDK/snippet.js

Prevent duplicate data if snippet is inserted twice

---

JavaScript/JavaScriptSDK/ajax/ajax.ts

Hotfix for ajax exception

---

JavaScript/JavaScriptSDK/ajax/ajax.ts

Disable Ajax monitoring in IE8 or older

---

API-reference.md
JavaScript/JavaScriptSDK.Tests/CheckinTests/Context/User.tests.ts
JavaScript/JavaScriptSDK.Tests/CheckinTests/appInsights.tests.ts
JavaScript/JavaScriptSDK/AppInsights.ts
JavaScript/JavaScriptSDK/Context/User.ts

Do not store authId in the cookie

---

.npmignore

Add source maps to npm package

---

JavaScript/JavaScriptSDK.Tests/CheckinTests/Telemetry/PageViewPerformance.tests.ts
JavaScript/JavaScriptSDK/Telemetry/PageViewPerformance.ts

detect all Google crawlers

---

JavaScript/JavaScriptSDK.Tests/E2ETests/SenderE2E.tests.ts
JavaScript/JavaScriptSDK/Sender.ts

pass text/plain data to sendBeacon

---

README.md

update js sdk snippet

---

Global.props
JavaScript/JavaScriptSDK/AppInsights.ts
bower.json
package.json

Publishing next version of JS SDK. Changes:
1. Bug fix for custom properties size.
2. changes for data correlation through new id field (changes are in but not enabled).

version update 1.0.15 -> 1.0.16

---

JavaScript/JavaScriptSDK/AppInsights.ts

Add id field back in as field is good for ingestion in Kusto.

Revert "temporarily remove pageview.id initialization" Add this back in as field is good for ingestion

---

Global.props
JavaScript/JavaScriptSDK/AppInsights.ts
bower.json
package.json

Need to capture logging for issue with parsing breeze response in 1.0.16.

version update 1.0.16 -> 1.0.17

---

cjs/package.json
coreSDK/applicationinsights-core.ts
coreSDK/package.json
gruntfile.js
tsconfigcommonjs.json

Add commonjs build and pack support for core SDK
#595

Add commonjs build and pack support for core SDK

---

package.json
tsconfig.json

Will publish a package with beta tag so users can try using this package hopefully to resolve this issue:
https://github.com/Microsoft/ApplicationInsights-JS/issues/615

do not generate types definition file

---

package.json
tsconfig.json

This reverts commit fba4ed5d5af9a2d3e4aebd0aaa830c260273d9ad.
We will keep the changes in a private branch while we do our testing using a beta package.

Revert "do not generate types definition file"

---

API-reference.md

Added correlationHeaderExcludedDomains to API reference

Added correlationHeaderExcludedDomains to API reference

---

JavaScript/JavaScriptSDK/SamplingScoreGenerator.ts
JavaScript/JavaScriptSDK/Sender.ts
JavaScript/JavaScriptSDK/UtilHelpers.ts
gruntfile.js
package.json
tslint.json

Run with `grunt tslint`
```
$ grunt tslint
Running "tslint:files" (tslint) task
Warning: The 'no-cookies' rule requires type information.
>> 75 files lint free.
Done.
```

Add SDL tslint

---

AISKU/README.md
AISKU/package.json
AISKU/src/Init.ts
AISKULight/package.json
AppInsightsCommon/package.json
AppInsightsCommon/src/Interfaces/PartAExtensions.ts
ApplicationInsights/package.json
extensions/applicationinsights-dependencies-js/package.json
extensions/applicationinsights-properties-js/package.json

- Add build badges for minified/gzipped sizes
- Fix bug preventing initialization from cdn

Fix initialization from cdn

---

AISKU/API.md
AISKU/Tests/applicationinsights.e2e.tests.ts
AISKU/package.json
AISKU/src/Initialization.ts
AISKULight/package.json
AppInsightsCommon/package.json
AppInsightsCommon/src/Interfaces/IConfig.ts
ApplicationInsights/package.json
ApplicationInsights/src/JavaScriptSDK/ApplicationInsights.ts
JavaScript/JavaScriptSDK/AppInsights.ts
extensions/applicationinsights-dependencies-js/package.json
extensions/applicationinsights-properties-js/package.json

- Fix ConfigurationManager bug
- Remove all instances of "browser" in package.json
- Bump dependencies to latest

Remove minified files from package.json, fix ConfigManager bug

---

extensions/applicationinsights-dependencies-js/Tests/Selenium/ajax.tests.ts
extensions/applicationinsights-dependencies-js/src/ajax.ts

- Checks for `DisabledPropertyName` in both `Request` and `RequestInit`

check for DisabledPropertyName for fetch collection

---

AISKU/README.md

Makes it clearer that not both things need to done.

Use bullet points for alternatives

---

AISKU/Tests/applicationinsights.e2e.tests.ts
AISKU/build.cmd
AISKU/package.json
AISKU/src/ApplicationInsightsDeprecated.ts
AISKU/src/Initialization.ts
AppInsightsCommon/package.json
AppInsightsCommon/src/Interfaces/IDependencyTelemetry.ts
ApplicationInsights/Tests/ApplicationInsights.tests.ts
ApplicationInsights/package.json
ApplicationInsights/src/JavaScriptSDK/ApplicationInsights.ts
extensions/applicationinsights-dependencies-js/package.json
extensions/applicationinsights-dependencies-js/src/ajax.ts
extensions/applicationinsights-properties-js/package.json
extensions/applicationinsights-properties-js/src/Context/Internal.ts
gruntfile.js

- Fix dependency telemetry fields
- update grunt file, build.cmd
- update SDK version number (2.0.2-beta)

Version updates

---

AISKU/README.md

Addresses #750 
Unsure of if it should be placed in a "Debug Settings" section, or if just having a paragraph in the config table is fine.

Add enableDebug blurb

---

ApplicationInsights/package.json
ApplicationInsights/src/JavaScriptSDK/ApplicationInsights.ts
extensions/applicationinsights-dependencies-js/package.json
extensions/applicationinsights-properties-js/package.json

Common changes for including props and measurements in part B for event.

update version for analytics, dependencies and properties extension

---

vNext/extensions/applicationinsights-react-native/README.md
vNext/extensions/applicationinsights-react-native/package.json

- Bumps version to `1.0.0-beta.0`

bump react-native plugin to 1.0.0-beta

---

vNext/AISKU/Tests/applicationinsights.e2e.tests.ts
vNext/AISKU/package.json
vNext/AISKULight/package.json
vNext/channels/applicationinsights-channel-js/package.json
vNext/channels/applicationinsights-channel-js/src/EnvelopeCreator.ts
vNext/extensions/applicationinsights-analytics-js/Tests/ApplicationInsights.tests.ts
vNext/extensions/applicationinsights-analytics-js/package.json
vNext/extensions/applicationinsights-analytics-js/src/JavaScriptSDK/ApplicationInsights.ts
vNext/extensions/applicationinsights-analytics-js/src/JavaScriptSDK/Telemetry/PageViewManager.ts
vNext/extensions/applicationinsights-analytics-js/src/JavaScriptSDK/Telemetry/PageViewPerformanceManager.ts
vNext/extensions/applicationinsights-dependencies-js/package.json
vNext/extensions/applicationinsights-properties-js/package.json
vNext/extensions/applicationinsights-react-native/package.json
vNext/shared/AppInsightsCommon/package.json
vNext/shared/AppInsightsCommon/src/Interfaces/IPageViewPerformanceTelemetry.ts
vNext/shared/AppInsightsCommon/src/Telemetry/PageViewPerformance.ts
vNext/shared/AppInsightsCommon/src/Util.ts
vNext/shared/AppInsightsCommon/src/applicationinsights-common.ts
vNext/shared/AppInsightsCore/package.json

PageViewPerformance property names updated
Enable sending system properties for PageViewPerformance
and Exceptions events.
Analytics track event overriding event name fix

PageViewPerformance property names updated

---

API.md
README.md
legacy_README.md
vNext/AISKU/package.json
vNext/AISKU/src/Initialization.ts
vNext/AISKULight/package.json
vNext/channels/applicationinsights-channel-js/Tests/Sender.tests.ts
vNext/channels/applicationinsights-channel-js/package.json
vNext/channels/applicationinsights-channel-js/src/EnvelopeCreator.ts
vNext/common/config/rush/npm-shrinkwrap.json
vNext/extensions/applicationinsights-analytics-js/package.json
vNext/extensions/applicationinsights-analytics-js/src/JavaScriptSDK/ApplicationInsights.ts
vNext/extensions/applicationinsights-dependencies-js/package.json
vNext/extensions/applicationinsights-properties-js/package.json
vNext/extensions/applicationinsights-properties-js/src/Context/Internal.ts
vNext/extensions/applicationinsights-react-native/package.json
vNext/shared/AppInsightsCommon/package.json
vNext/shared/AppInsightsCore/package.json

- Move vNext readme to frontpage
- bump package versions to `2.0.0-rc1`

release rc1

---

vNext/AISKU/package.json
vNext/AISKU/src/Initialization.ts
vNext/AISKULight/package.json
vNext/channels/applicationinsights-channel-js/package.json
vNext/channels/applicationinsights-channel-js/src/EnvelopeCreator.ts
vNext/extensions/applicationinsights-analytics-js/package.json
vNext/extensions/applicationinsights-analytics-js/src/JavaScriptSDK/ApplicationInsights.ts
vNext/extensions/applicationinsights-dependencies-js/package.json
vNext/extensions/applicationinsights-properties-js/package.json
vNext/extensions/applicationinsights-properties-js/src/Context/Internal.ts
vNext/extensions/applicationinsights-react-native/package.json
vNext/shared/AppInsightsCommon/package.json
vNext/shared/AppInsightsCore/package.json

Includes #825, #827, #829, #831, #833

release 2.0.0-rc2

---

vNext/AISKU/package.json
vNext/AISKU/src/Initialization.ts
vNext/AISKULight/package.json
vNext/channels/applicationinsights-channel-js/package.json
vNext/channels/applicationinsights-channel-js/src/EnvelopeCreator.ts
vNext/extensions/applicationinsights-analytics-js/package.json
vNext/extensions/applicationinsights-analytics-js/src/JavaScriptSDK/ApplicationInsights.ts
vNext/extensions/applicationinsights-dependencies-js/package.json
vNext/extensions/applicationinsights-properties-js/package.json
vNext/extensions/applicationinsights-properties-js/src/Context/Internal.ts
vNext/extensions/applicationinsights-react-native/package.json
vNext/shared/AppInsightsCommon/package.json
vNext/shared/AppInsightsCore/package.json

release 2.0.0-rc3

---

README.md
vNext/AISKU/Tests/applicationinsights.e2e.tests.ts
vNext/AISKU/package.json
vNext/AISKU/src/Initialization.ts
vNext/AISKULight/package.json
vNext/channels/applicationinsights-channel-js/Tests/Sender.tests.ts
vNext/channels/applicationinsights-channel-js/package.json
vNext/channels/applicationinsights-channel-js/src/EnvelopeCreator.ts
vNext/extensions/applicationinsights-analytics-js/package.json
vNext/extensions/applicationinsights-analytics-js/src/JavaScriptSDK/ApplicationInsights.ts
vNext/extensions/applicationinsights-dependencies-js/package.json
vNext/extensions/applicationinsights-properties-js/package.json
vNext/extensions/applicationinsights-properties-js/src/Context/Internal.ts
vNext/extensions/applicationinsights-react-native/package.json
vNext/shared/AppInsightsCommon/package.json
vNext/shared/AppInsightsCore/package.json

Includes #839, #840, #842, #844

bump versions to 2.0.0-rc4

---

vNext/extensions/applicationinsights-react-js/src/ReactPlugin.ts

Updating priority because current have duplicated value with properties extension

Updating react extension priority

---

vNext/extensions/applicationinsights-react-js/package.json

Previous package was manually published and it was not correctly built

Updating version of react  extension

---

JavaScript/JavaScriptSDK.Tests/CheckinTests/Util.tests.ts
JavaScript/JavaScriptSDK/Util.ts

add parseHost to legacy SDK

---

vNext/channels/applicationinsights-channel-js/src/EnvelopeCreator.ts
vNext/shared/AppInsightsCommon/src/Telemetry/PageViewPerformance.ts

Addresses https://github.com/microsoft/ApplicationInsights-JS/issues/877

fix missing part b in pageviewperformance

---

vNext/extensions/applicationinsights-analytics-js/src/JavaScriptSDK/ApplicationInsights.ts
vNext/extensions/applicationinsights-dependencies-js/src/ajax.ts
vNext/shared/AppInsightsCommon/Tests/Exception.tests.ts
vNext/shared/AppInsightsCommon/src/Telemetry/Exception.ts

- common: Add missing internal fields to Exception (`id`, `problemGroup`, etc)
- dependencies/analytics: make internal-only members protected instead of public

change protected members

---

vNext/extensions/applicationinsights-analytics-js/src/JavaScriptSDK/ApplicationInsights.ts
vNext/shared/AppInsightsCommon/src/Interfaces/IExceptionTelemetry.ts
vNext/shared/AppInsightsCommon/src/Telemetry/Exception.ts

exception: add id to part b

---

vNext/extensions/applicationinsights-react-js/README.md

Makes TypeScript a bit happier ;-)

[README] Fix sample configuration settings

---

README.md

#906 
Adds note to upgrade guide on usage of trace extension

minor: add telemetryTrace to docs

---

README.md

Add missing `properties` in `appInsights.properties.context.telemetryTrace.traceID` example

Update README.md Upgrade appInsights.context

---

vNext/AISKU/package.json
vNext/AISKU/src/Initialization.ts
vNext/AISKULight/package.json
vNext/channels/applicationinsights-channel-js/Tests/Sender.tests.ts
vNext/channels/applicationinsights-channel-js/package.json
vNext/channels/applicationinsights-channel-js/src/EnvelopeCreator.ts
vNext/channels/applicationinsights-channel-js/src/TelemetryValidation/EventValidator.ts
vNext/extensions/applicationinsights-analytics-js/package.json
vNext/extensions/applicationinsights-analytics-js/src/JavaScriptSDK/ApplicationInsights.ts
vNext/extensions/applicationinsights-dependencies-js/package.json
vNext/extensions/applicationinsights-properties-js/package.json
vNext/extensions/applicationinsights-properties-js/src/Context/Internal.ts
vNext/extensions/applicationinsights-react-js/package.json
vNext/extensions/applicationinsights-react-native/package.json
vNext/shared/AppInsightsCommon/package.json
vNext/shared/AppInsightsCore/package.json

bump to 2.0.1

---

vNext/extensions/applicationinsights-react-js/package.json
vNext/extensions/applicationinsights-react-js/rollup.config.js

Bumps react plugin to `2.0.2`
Adds commonjs plugin to react plugin rollup to resolve user jest failures

resolve react plugin jest failures

---

API.md

https://github.com/microsoft/ApplicationInsights-JS/blob/master/vNext/shared/AppInsightsCommon/src/Interfaces/IDependencyTelemetry.ts
Change optional fields to match TS
closes #929

docs: match RDD with TS

---

CONTRIBUTING.md
README.md

Adding contributing.md and moving relevant content into contributing.md

Adding Contributing.md file

---

README.md
vNext/AISKU/package.json
vNext/AISKU/src/Initialization.ts
vNext/AISKULight/package.json
vNext/channels/applicationinsights-channel-js/Tests/Sender.tests.ts
vNext/channels/applicationinsights-channel-js/package.json
vNext/channels/applicationinsights-channel-js/src/EnvelopeCreator.ts
vNext/extensions/applicationinsights-analytics-js/package.json
vNext/extensions/applicationinsights-analytics-js/src/JavaScriptSDK/ApplicationInsights.ts
vNext/extensions/applicationinsights-dependencies-js/package.json
vNext/extensions/applicationinsights-properties-js/package.json
vNext/extensions/applicationinsights-properties-js/src/Context/Internal.ts
vNext/extensions/applicationinsights-react-js/package.json
vNext/extensions/applicationinsights-react-native/package.json
vNext/shared/AppInsightsCommon/package.json
vNext/shared/AppInsightsCore/package.json

Bump package and `Version` strings to 2.1.0

^minor: bump to 2.1.0

---

vNext/extensions/applicationinsights-react-js/package.json
vNext/extensions/applicationinsights-react-js/src/ReactPlugin.ts

react: priority to 185, bump to 2.1.1

---

CONTRIBUTING.md
README.md
vNext/extensions/applicationinsights-react-js/README.md

Updating install and build instructions #986
Fixing documentation issue for React plugin  #964

Updating documentation

---

vNext/shared/AppInsightsCore/src/JavaScriptSDK/ChannelController.ts

Channel could need a reference to next plugin during initialization

setNextPlugin need to be called before init

---

vNext/shared/AppInsightsCore/src/JavaScriptSDK/ChannelController.ts

setNextPlugin need to be called before init when channels config is not provided

Channel initialization update

---

vNext/AISKU/package.json
vNext/AISKU/src/Initialization.ts
vNext/AISKULight/package.json
vNext/channels/applicationinsights-channel-js/Tests/Sender.tests.ts
vNext/channels/applicationinsights-channel-js/package.json
vNext/channels/applicationinsights-channel-js/src/EnvelopeCreator.ts
vNext/extensions/applicationinsights-analytics-js/package.json
vNext/extensions/applicationinsights-analytics-js/src/JavaScriptSDK/ApplicationInsights.ts
vNext/extensions/applicationinsights-dependencies-js/package.json
vNext/extensions/applicationinsights-properties-js/package.json
vNext/extensions/applicationinsights-properties-js/src/Context/Internal.ts
vNext/extensions/applicationinsights-react-js/package.json
vNext/extensions/applicationinsights-react-native/package.json
vNext/shared/AppInsightsCommon/package.json
vNext/shared/AppInsightsCore/package.json

Update package versions to `2.2.1`

chore: bump versions to 2.2.1

---

vNext/channels/applicationinsights-channel-js/Tests/Sender.tests.ts
vNext/shared/AppInsightsCommon/src/Telemetry/RemoteDependencyData.ts

adjust format of dependency.target when correlationContext exists

---

vNext/AISKU/package.json
vNext/AISKU/src/Initialization.ts
vNext/AISKULight/package.json
vNext/channels/applicationinsights-channel-js/Tests/Sender.tests.ts
vNext/channels/applicationinsights-channel-js/package.json
vNext/channels/applicationinsights-channel-js/src/EnvelopeCreator.ts
vNext/extensions/applicationinsights-analytics-js/package.json
vNext/extensions/applicationinsights-analytics-js/src/JavaScriptSDK/ApplicationInsights.ts
vNext/extensions/applicationinsights-dependencies-js/package.json
vNext/extensions/applicationinsights-properties-js/package.json
vNext/extensions/applicationinsights-properties-js/src/Context/Internal.ts
vNext/extensions/applicationinsights-react-js/package.json
vNext/extensions/applicationinsights-react-native/package.json
vNext/shared/AppInsightsCommon/package.json
vNext/shared/AppInsightsCore/package.json

Release 2.2.2

---

README.md

docs(readme): add trackPageView to NPM setup

---

AISKU/package.json
AISKULight/package.json
channels/applicationinsights-channel-js/Tests/Sender.tests.ts
channels/applicationinsights-channel-js/package.json
channels/applicationinsights-channel-js/src/EnvelopeCreator.ts
extensions/applicationinsights-analytics-js/package.json
extensions/applicationinsights-analytics-js/src/JavaScriptSDK/ApplicationInsights.ts
extensions/applicationinsights-angular-js/package.json
extensions/applicationinsights-dependencies-js/package.json
extensions/applicationinsights-properties-js/package.json
extensions/applicationinsights-properties-js/src/Context/Internal.ts
extensions/applicationinsights-react-js/package.json
extensions/applicationinsights-react-native/package.json
shared/AppInsightsCommon/package.json
shared/AppInsightsCore/package.json

chore: bump version to 2.3.0

---

extensions/applicationinsights-properties-js/src/Context/TelemetryTrace.ts

bugfix: telemetryTrace name property is overwritten

---

.travis.yml
AISKU/package.json
AISKULight/package.json
channels/applicationinsights-channel-js/Tests/Sender.tests.ts
channels/applicationinsights-channel-js/package.json
channels/applicationinsights-channel-js/src/EnvelopeCreator.ts
common/config/rush/npm-shrinkwrap.json
extensions/applicationinsights-analytics-js/package.json
extensions/applicationinsights-analytics-js/src/JavaScriptSDK/ApplicationInsights.ts
extensions/applicationinsights-angular-js/package.json
extensions/applicationinsights-dependencies-js/package.json
extensions/applicationinsights-properties-js/package.json
extensions/applicationinsights-properties-js/src/Context/Internal.ts
extensions/applicationinsights-react-js/package.json
extensions/applicationinsights-react-native/package-lock.json
extensions/applicationinsights-react-native/package.json
extensions/applicationinsights-react-native/src/ReactNativePlugin.ts
package-lock.json
package.json
shared/AppInsightsCommon/package.json
shared/AppInsightsCore/package.json

- Bump versions to 2.3.1
- Add react native tests to CI

chore: bump versions to 2.3.1

---

.travis.yml

Temporarily disable the react native tests from build

Temporarily disable the react native tests from build

---

shared/AppInsightsCore/src/JavaScriptSDK/DiagnosticLogger.ts

fix: console logging not honoring setting

---

AISKU/README.md

Link does not work on npmjs page
https://www.npmjs.com/package/@microsoft/applicationinsights-web

docs: update dead npmjs readme link

---

README.md

readme: fix markdown hyperlink

readme: fix markdown hyperlink

---

tools/rollup-es3/package.json

Remove unnecessary postinstall step from package that breaks installations

Fixup Rollup ES3 plugin package.json

---

AISKU/rollup.config.js
AISKU/scripts/uploadFilesToAzureStorage.ps1
AISKULight/rollup.config.js
README.md
channels/applicationinsights-channel-js/rollup.config.js
extensions/applicationinsights-analytics-js/rollup.config.js
extensions/applicationinsights-angular-js/rollup.config.js
extensions/applicationinsights-dependencies-js/rollup.config.js
extensions/applicationinsights-properties-js/rollup.config.js
extensions/applicationinsights-react-js/rollup.config.js
shared/AppInsightsCommon/rollup.config.js
shared/AppInsightsCore/rollup.config.js
tools/rollup-es3/Tests/Es3Rollup.Tests.ts
tools/rollup-es3/src/ImportCheck.ts
tools/rollup-es3/src/applicationinsignts-rollup-es3.ts
tools/rollup-es3/src/es3/Es3Poly.ts
tools/rollup-es3/src/es3/Es3Tokens.ts
tools/rollup-es3/src/es3/FormatError.ts
tools/rollup-es3/src/es3/Interfaces.ts

- Add importCheck() rollup plugin

Add additional checks and polyfil for TypeScript get translations for constants

---

AISKU/package.json
AISKU/rollup.config.js
AISKU/src/Init.ts
AISKULight/package.json
RELEASES.md
channels/applicationinsights-channel-js/Tests/Sender.tests.ts
channels/applicationinsights-channel-js/package.json
channels/applicationinsights-channel-js/src/EnvelopeCreator.ts
extensions/applicationinsights-analytics-js/package.json
extensions/applicationinsights-analytics-js/src/JavaScriptSDK/ApplicationInsights.ts
extensions/applicationinsights-angular-js/package.json
extensions/applicationinsights-dependencies-js/package.json
extensions/applicationinsights-properties-js/package.json
extensions/applicationinsights-properties-js/src/Context/Internal.ts
extensions/applicationinsights-react-js/package.json
shared/AppInsightsCommon/package.json
shared/AppInsightsCore/package.json

Disable window namespace overwrite

---

extensions/applicationinsights-dependencies-js/Tests/Selenium/ajax.tests.ts
extensions/applicationinsights-dependencies-js/src/ajax.ts

fix response type error

---

AISKU/src/Initialization.ts

Corrected a few spelling mistakes in the method comment for setAuthenticatedUserContext.

Fixed spelling errors

---

extensions/applicationinsights-properties-js/Tests/Selenium/properties.tests.ts
extensions/applicationinsights-properties-js/src/Context/TelemetryTrace.ts
extensions/applicationinsights-properties-js/src/TelemetryContext.ts

add sanitizer for operationName

---

AISKU/Tests/Selenium/Tests.html
AISKU/Tests/applicationinsights.e2e.tests.ts
channels/applicationinsights-channel-js/src/Sender.ts
common/config/rush/npm-shrinkwrap.json
extensions/applicationinsights-dependencies-js/Tests/Selenium/ajax.tests.ts
extensions/applicationinsights-dependencies-js/Tests/Selenium/dependencies.tests.ts
extensions/applicationinsights-dependencies-js/src/ajax.ts

[BUG] App Insights fails when the XHR object is not extensible (or frozen) #1217

[BUG] App Insights initialization setting 'enableAjaxErrorStatusText is not working #1186

---

AISKU/package.json
AISKULight/package.json
RELEASES.md
channels/applicationinsights-channel-js/Tests/Sender.tests.ts
channels/applicationinsights-channel-js/package.json
channels/applicationinsights-channel-js/src/EnvelopeCreator.ts
extensions/applicationinsights-analytics-js/package.json
extensions/applicationinsights-analytics-js/src/JavaScriptSDK/ApplicationInsights.ts
extensions/applicationinsights-angular-js/package.json
extensions/applicationinsights-dependencies-js/package.json
extensions/applicationinsights-properties-js/package.json
extensions/applicationinsights-properties-js/src/Context/Internal.ts
extensions/applicationinsights-react-js/package.json
extensions/applicationinsights-react-native/package.json
shared/AppInsightsCommon/package.json
shared/AppInsightsCore/package.json

Needs PR #1218 as it holds the payload for the changes from 2.5.1

[Release] Increase version to 2.5.2

---

extensions/applicationinsights-react-js/package.json

mark react as peer/dev dep

---

AISKU/src/Initialization.ts
extensions/applicationinsights-analytics-js/src/JavaScriptSDK/ApplicationInsights.ts
extensions/applicationinsights-debugplugin-js/rollup.config.js
extensions/applicationinsights-debugplugin-js/sample/public/sample.js
extensions/applicationinsights-debugplugin-js/src/DebugPlugin.ts
extensions/applicationinsights-debugplugin-js/src/applicationinsights-debugplugin-js.ts
extensions/applicationinsights-debugplugin-js/src/components/Dashboard.ts
extensions/applicationinsights-debugplugin-js/src/components/LogEntry.ts
extensions/applicationinsights-debugplugin-js/src/components/debugBins.ts
extensions/applicationinsights-debugplugin-js/src/components/filterList.ts
extensions/applicationinsights-debugplugin-js/src/components/helpers.ts
extensions/applicationinsights-debugplugin-js/src/components/styleNodeSrc.ts
extensions/applicationinsights-debugplugin-js/src/interfaces/IDebugPluginConfig.ts
extensions/applicationinsights-debugplugin-js/src/interfaces/ITelemetryPlugin.ts
shared/AppInsightsCommon/src/Util.ts
shared/AppInsightsCore/src/JavaScriptSDK.Interfaces/IAppInsightsCore.ts
shared/AppInsightsCore/src/JavaScriptSDK.Interfaces/IConfiguration.ts
shared/AppInsightsCore/src/JavaScriptSDK.Interfaces/INotificationListener.ts
shared/AppInsightsCore/src/JavaScriptSDK.Interfaces/INotificationManager.ts
shared/AppInsightsCore/src/JavaScriptSDK.Interfaces/IPerfEvent.ts
shared/AppInsightsCore/src/JavaScriptSDK.Interfaces/IPerfManager.ts
shared/AppInsightsCore/src/JavaScriptSDK/AppInsightsCore.ts
shared/AppInsightsCore/src/JavaScriptSDK/BaseCore.ts
shared/AppInsightsCore/src/JavaScriptSDK/CoreUtils.ts
shared/AppInsightsCore/src/JavaScriptSDK/DiagnosticLogger.ts
shared/AppInsightsCore/src/JavaScriptSDK/NotificationManager.ts
shared/AppInsightsCore/src/JavaScriptSDK/PerfManager.ts
shared/AppInsightsCore/src/JavaScriptSDK/TelemetryPluginChain.ts
shared/AppInsightsCore/src/applicationinsights-core-js.ts

- Added optional performance monitoring hooks - IPerfManager, IPerfEvent, IPerfManagerProvider
Update DebugPlugin (Lots of  updates)
- Fixed performance issues (identified by new Performance monitoring)
- lazily initialize the UX / DOM
- Fixed the namespace used in sample.js
- Added simple wildcard search matching
- Added search highlight matching
- Update search triggering to automatically search during typing delay
- Started formalizing the Debug Plugin config settings
- Made the lookup of object (extensions / plugins) generic
- Added NotificationManager hooks
- Hide functions by default in the dashboard
- Reworked dashboard controls so they don't scroll
- Added a clear button
- Added a close dashboard  button
- blah, blah, blah -- documentation needs updating now.

Add Performance / Testing support #1335 and [BUG] DebugPlugin various updates #1333

---

RELEASES.md
extensions/applicationinsights-react-js/package.json
extensions/applicationinsights-react-js/src/useTrackMetric.ts
extensions/applicationinsights-react-js/src/withAITracking.tsx
extensions/applicationinsights-react-native/package-lock.json
extensions/applicationinsights-react-native/package.json

[Release][React] - Increase versions React 3.0.3
[Release][ReactNative] - Increase versions ReactNative 2.2.7

[Release][React] - Increase versions React 3.0.3

---

AISKU/rollup.config.js
AISKU/scripts/listCdnVersions.ps1
AISKU/scripts/publishReleaseToCdn.ps1
AISKU/scripts/setActiveCdnVersion.ps1

- Also publish an iife module format to skip the define loading

Error Mismatched anonymous define() module #1018

---

shared/AppInsightsCommon/src/Interfaces/IConfig.ts

correlationHeaderExcludePatterns added to IConfig

correlationHeaderExcludePatterns added to IConfig

---

AISKU/src/Initialization.ts
AISKU/src/applicationinsights-web.ts
shared/AppInsightsCore/src/JavaScriptSDK.Interfaces/IAppInsightsCore.ts

exporting perf related classes in AISKU.

exporting perf related classes in AISKU

---

extensions/applicationinsights-react-js/package.json

latest update of @types/cheerio causing this issue
older version "@types/cheerio": "0.22.13" added to devdepedency

using older version of types/cheerio dependecy

---

AISKU/scripts/listCdnVersions.ps1
AISKU/scripts/publishReleaseToCdn.ps1
AISKU/scripts/setActiveCdnVersion.ps1
extensions/applicationinsights-debugplugin-js/scripts/listCdnVersions.ps1
extensions/applicationinsights-debugplugin-js/scripts/publishReleaseToCdn.ps1
extensions/applicationinsights-debugplugin-js/scripts/setActiveCdnVersion.ps1

- Supports when the user is only a Contributor to the storage account
- Does not have access to create SasTokens or access subscription keys

Update publishing scripts to support automation

---

RELEASES.md
common/config/rush/npm-shrinkwrap.json
extensions/applicationinsights-angularplugin-js/package.json
extensions/applicationinsights-react-js/package.json
extensions/applicationinsights-react-native/package.json

[Release][ReactNative] - Increase versions ReactNative 2.2.8
[Release][AngularPlugin] - Increase versions ReactNative 2.5.9

[Release][React] - Increase versions to React 3.0.4

---

nuget/Microsoft.ApplicationInsights.JavaScript.Snippet.nuspec

https://devdiv.visualstudio.com/DevDiv/_wiki/wikis/DevDiv.wiki/11557/Publishing-Microsoft-packages?anchor=publishing-microsoft-packages-on-nuget.org

Updating nuget copyright

---

RELEASES.md
extensions/applicationinsights-angularplugin-js/package.json
extensions/applicationinsights-react-js/package.json
extensions/applicationinsights-react-native/package.json

[Release][ReactNative] - Increase ReactNative Plugin to version 2.2.9
[Release][Angular] - Increase Angular Plugin to version 2.5.10

[Release][React] - Increase React plugin to version 3.0.5

---

extensions/applicationinsights-react-js/README.md

Suggestion from https://github.com/microsoft/ApplicationInsights-JS/issues/991#issuecomment-757067484

Adding link to MS docs

---

AISKU/package.json
AISKULight/package.json
common/config/rush/npm-shrinkwrap.json
extensions/applicationinsights-clickanalytics-js/package.json
extensions/applicationinsights-debugplugin-js/package.json
scripts/dtsgen.js

- Convert PowerShell script to a nodejs one.

[BUG] New dts gneration doesn't work when the environment doesn't have powershell #1473

---

channels/applicationinsights-channel-js/src/TelemetryProcessors/Sample.ts
extensions/applicationinsights-analytics-js/src/JavaScriptSDK/ApplicationInsights.ts
extensions/applicationinsights-analytics-js/src/JavaScriptSDK/Telemetry/PageViewManager.ts
extensions/applicationinsights-analytics-js/src/JavaScriptSDK/Telemetry/PageVisitTimeManager.ts
extensions/applicationinsights-clickanalytics-js/src/ClickAnalyticsPlugin.ts
extensions/applicationinsights-clickanalytics-js/src/DataCollector.ts
extensions/applicationinsights-clickanalytics-js/src/common/Utils.ts
extensions/applicationinsights-clickanalytics-js/src/handlers/AutoCaptureHandler.ts
extensions/applicationinsights-clickanalytics-js/src/handlers/DomContentHandler.ts
extensions/applicationinsights-debugplugin-js/src/DebugPlugin.ts
extensions/applicationinsights-debugplugin-js/src/components/Dashboard.ts
extensions/applicationinsights-debugplugin-js/src/components/LogEntry.ts
extensions/applicationinsights-debugplugin-js/src/components/helpers.ts
extensions/applicationinsights-dependencies-js/src/ajax.ts
extensions/applicationinsights-dependencies-js/src/ajaxRecord.ts
extensions/applicationinsights-dependencies-js/src/ajaxUtils.ts
extensions/applicationinsights-properties-js/Tests/Selenium/properties.tests.ts
extensions/applicationinsights-properties-js/src/Context/Session.ts
extensions/applicationinsights-properties-js/src/Context/User.ts
extensions/applicationinsights-properties-js/src/PropertiesPlugin.ts
extensions/applicationinsights-properties-js/src/TelemetryContext.ts

- Stop using CoreUtils directly

Extensions - Tree-Shaking enhancements

---

channels/applicationinsights-channel-js/src/EnvelopeCreator.ts
channels/applicationinsights-channel-js/src/Offline.ts
channels/applicationinsights-channel-js/src/SendBuffer.ts
channels/applicationinsights-channel-js/src/Sender.ts
channels/applicationinsights-channel-js/src/Serializer.ts
channels/applicationinsights-channel-js/src/TelemetryProcessors/Sample.ts

- Stop using CoreUtils directly

Channels - Tree-Shaking enhancements

---

AISKU/Tests/SnippetInitialization.Tests.ts
shared/AppInsightsCommon/src/ConnectionStringParser.ts
shared/AppInsightsCommon/src/DomHelperFuncs.ts
shared/AppInsightsCommon/src/HelperFuncs.ts
shared/AppInsightsCommon/src/Interfaces/IConfig.ts
shared/AppInsightsCommon/src/Telemetry/Common/DataSanitizer.ts
shared/AppInsightsCommon/src/Telemetry/Common/Envelope.ts
shared/AppInsightsCommon/src/Telemetry/Exception.ts
shared/AppInsightsCommon/src/TelemetryItemCreator.ts
shared/AppInsightsCommon/src/Util.ts
shared/AppInsightsCommon/src/applicationinsights-common.ts

- Stop using CoreUtils directly

Common - Tree-Shaking enhancements

---

AISKU/src/Initialization.ts
common/config/rush/npm-shrinkwrap.json
extensions/applicationinsights-analytics-js/src/JavaScriptSDK/ApplicationInsights.ts
extensions/applicationinsights-analytics-js/src/JavaScriptSDK/Telemetry/PageViewManager.ts
extensions/applicationinsights-analytics-js/src/JavaScriptSDK/Telemetry/PageViewPerformanceManager.ts
extensions/applicationinsights-dependencies-js/Tests/Selenium/ajax.tests.ts
extensions/applicationinsights-dependencies-js/src/ajax.ts
extensions/applicationinsights-dependencies-js/src/ajaxRecord.ts
shared/AppInsightsCommon/src/Util.ts
shared/AppInsightsCommon/src/applicationinsights-common.ts

[Bug] Ajax tracking for XHR and fetch is not always setting the starttime correctly #1478

---

extensions/applicationinsights-analytics-js/src/JavaScriptSDK/ApplicationInsights.ts

update operation name

---

extensions/applicationinsights-analytics-js/src/JavaScriptSDK/Telemetry/PageViewPerformanceManager.ts

bug fix - update network time calculation in pv performance manager

---

RELEASES.md
extensions/applicationinsights-react-js/package.json
extensions/applicationinsights-react-native/package.json

[Release][React-Native] Increase React Native Plugin to version 2.3.1

[Release][React] Increase React Plugin to version 3.1.1

---

RELEASES.md
extensions/applicationinsights-react-js/package.json
extensions/applicationinsights-react-native/package.json

[Release][React-Native] Increase React Native Plugin to version 2.3.3

[Release][React] Increase React Plugin to version 3.1.3

---

RELEASES.md
extensions/applicationinsights-react-js/package.json
extensions/applicationinsights-react-native/package.json

[Release][ReactNative] Increase version to 2.3.4

[Release][React] Increase version to 3.1.4

---

RELEASES.md
extensions/applicationinsights-react-js/package.json
extensions/applicationinsights-react-native/package.json

[Release][ReactNative] Increase version to 2.3.5

[Release][React] Increase version to 3.1.5

---

tools/release-tools/setVersion.js

- Better handling for autmatically generating beta release

Update automatic version script

---

extensions/applicationinsights-react-js/README.md

Update readme for react router v6 (enable auto tracking routes changes)

update react plugin readme

---

tools/release-tools/setVersion.js
version.json

This is to support automated "beta" which will bump the minor version, but future ones will only need a "patch"

Update version update script to support default "next" release version (major/minor) not just patch

---

extensions/applicationinsights-react-js/src/useTrackMetric.ts

Add custom properties argument to useTrackMetric

Allow including custom properties in useTrackMetric

---

AISKU/src/Initialization.ts
channels/applicationinsights-channel-js/src/TelemetryProcessors/Sample.ts
common/config/rush/npm-shrinkwrap.json
shared/AppInsightsCommon/src/Interfaces/IConfig.ts
shared/AppInsightsCore/src/JavaScriptSDK.Interfaces/IConfiguration.ts
shared/AppInsightsCore/src/JavaScriptSDK/BaseCore.ts
shared/AppInsightsCore/src/JavaScriptSDK/BaseTelemetryPlugin.ts
shared/AppInsightsCore/src/JavaScriptSDK/ProcessTelemetryContext.ts
shared/AppInsightsCore/src/JavaScriptSDK/TelemetryHelpers.ts
tools/release-tools/setVersion.js
tools/rollup-es3/src/ImportCheck.ts
tools/rollup-es3/src/es3/Es3Check.ts

This is a pre-requisite PR before the 2.8.0 release

Finalize and Update the processTelemetry helper functions

---

RELEASES.md

Highlighting the potential breaking change in the release notes

[BUG] Adding new on-by-default telemetry is a breaking change, and should involve a major version bump #1808

---

.github/workflows/ci.yml
.github/workflows/codeql-analysis.yml
AISKU/package.json
AISKU/src/ApplicationInsightsDeprecated.ts
AISKU/src/Initialization.ts
AISKULight/package.json
channels/applicationinsights-channel-js/package.json
common/Tests/Framework/package.json
common/config/rush/npm-shrinkwrap.json
extensions/applicationinsights-analytics-js/package.json
extensions/applicationinsights-clickanalytics-js/package.json
extensions/applicationinsights-debugplugin-js/package.json
extensions/applicationinsights-debugplugin-js/src/DebugPlugin.ts
extensions/applicationinsights-debugplugin-js/src/components/Dashboard.ts
extensions/applicationinsights-debugplugin-js/src/components/filterList.ts
extensions/applicationinsights-debugplugin-js/src/components/helpers.ts
extensions/applicationinsights-dependencies-js/package.json
extensions/applicationinsights-perfmarkmeasure-js/package.json
extensions/applicationinsights-properties-js/package.json
extensions/applicationinsights-react-js/package.json
extensions/applicationinsights-react-native/package.json
shared/AppInsightsCommon/package.json
shared/AppInsightsCommon/src/Util.ts
shared/AppInsightsCore/package.json
shared/AppInsightsCore/src/JavaScriptSDK/DiagnosticLogger.ts
tools/chrome-debug-extension/package.json

This is to "fix" the 2.7.x branch with 2.7.5 so that IE8 Support is re-enabled.
I'll then follow this up with an Angular11 release using the new dynamicProto() and v2.7.5 of Application Insights

[BUG] IE8 Support was broken by several components #1823

---

README.md

Update README.md to redirect to Node.JS

---

AISKU/Tests/Manual/HelloWorld.html
AISKU/Tests/Perf/src/AISKUPerf.ts
AISKU/package.json
AISKULight/package.json
RELEASES.md
channels/applicationinsights-channel-js/Tests/Unit/src/Sender.tests.ts
channels/applicationinsights-channel-js/package.json
channels/applicationinsights-channel-js/src/EnvelopeCreator.ts
common/Tests/Framework/package.json
common/config/rush/npm-shrinkwrap.json
extensions/applicationinsights-analytics-js/package.json
extensions/applicationinsights-analytics-js/src/JavaScriptSDK/ApplicationInsights.ts
extensions/applicationinsights-clickanalytics-js/package.json
extensions/applicationinsights-clickanalytics-js/src/ClickAnalyticsPlugin.ts
extensions/applicationinsights-debugplugin-js/package.json
extensions/applicationinsights-dependencies-js/package.json
extensions/applicationinsights-perfmarkmeasure-js/package.json
extensions/applicationinsights-properties-js/package.json
extensions/applicationinsights-properties-js/src/Context/Internal.ts
extensions/applicationinsights-react-js/package.json
extensions/applicationinsights-react-native/package.json
package.json
shared/AppInsightsCommon/package.json
shared/AppInsightsCore/package.json
tools/chrome-debug-extension/manifest.json
tools/chrome-debug-extension/package.json
version.json

- Updates to dynamicProto v1.1.6 and add manual test page
- [IE8] Fix in 1.1.5 only handles 2 levels of dynamically nested classes #50

[Release] Increase version to 2.7.6

---

AISKU/Tests/Manual/HelloWorld.html
AISKU/package.json
AISKULight/package.json
channels/applicationinsights-channel-js/package.json
common/Tests/Framework/package.json
common/config/rush/npm-shrinkwrap.json
extensions/applicationinsights-analytics-js/package.json
extensions/applicationinsights-clickanalytics-js/package.json
extensions/applicationinsights-debugplugin-js/package.json
extensions/applicationinsights-dependencies-js/package.json
extensions/applicationinsights-perfmarkmeasure-js/package.json
extensions/applicationinsights-properties-js/package.json
extensions/applicationinsights-react-js/package.json
extensions/applicationinsights-react-native/package.json
shared/AppInsightsCommon/package.json
shared/AppInsightsCore/package.json
tools/chrome-debug-extension/manifest.json
tools/chrome-debug-extension/package.json

- [IE8] Fix in 1.1.5 only handles 2 levels of dynamically nested classes #50

Update to dynamicProto v1.1.6 and add manual test page

---

common/config/rush/npm-shrinkwrap.json
package.json
rush.json

- Update npm to 8.13.2
- Update rush to 5.75.0

Address Component Governance issues

---

shared/AppInsightsCommon/Tests/Unit/src/Exception.tests.ts
shared/AppInsightsCommon/src/Telemetry/Exception.ts

related issue: https://github.com/microsoft/ApplicationInsights-JS/issues/1679

[Task]15465575: add getErrorstackObj from reason.stack 

---

README.md

* Fixed release notes, previously used a deprecated file.
The file linked in the 'Changelist' had been deprecated, moved to https://github.com/microsoft/ApplicationInsights-JS/releases , an active and dynamically supported list of releases.
* Update README.md
Co-authored-by: Nev <54870357+MSNev@users.noreply.github.com>

[Beta] Merge remote-tracking branch 'upstream/master' into MSNev/beta

---

shared/AppInsightsCore/Tests/Unit/src/DynamicConfig.Tests.ts
shared/AppInsightsCore/src/Config/DynamicProperty.ts

- when the referenced property is not an object/array (ie. undefined or null)
- we are assigning a referenced object/array to null / undefined

Address dynamic corner-cases  - Task 15982357: [Beta] [AI] Dynamic config for Properties extension

---

common/config/rush/npm-shrinkwrap.json
shared/AppInsightsCommon/Tests/Unit/src/ThrottleMgr.tests.ts
shared/AppInsightsCommon/src/Interfaces/IThrottleMgr.ts
shared/AppInsightsCommon/src/ThrottleMgr.ts

https://github.com/microsoft/ApplicationInsights-JS/issues/1979

[Beta][Task]16961420: fix throttleMgr tests

---

README.md
common/config/rush/npm-shrinkwrap.json
examples/README.md
examples/shared-worker/README.md
examples/shared-worker/SharedWorker.html
examples/shared-worker/package.json
examples/shared-worker/rollup.config.js
examples/shared-worker/src/example-shared-worker.ts
examples/shared-worker/src/interfaces/IExampleMessage.ts
examples/shared-worker/src/worker-npm-init.ts
examples/shared-worker/src/worker.ts
examples/shared-worker/src/worker2.ts
examples/shared-worker/tsconfig.json
extensions/applicationinsights-dependencies-js/src/ajax.ts
gruntfile.js
rush.json
shared/AppInsightsCore/src/JavaScriptSDK/InstrumentHooks.ts
tools/release-tools/setVersion.js

- Also add a Shared Worker example

[Beta] [BUG] SharedWorker does not Instrument fetch correctly #1996

---

README.md
common/config/rush/npm-shrinkwrap.json
examples/README.md
examples/shared-worker/README.md
examples/shared-worker/SharedWorker.html
examples/shared-worker/package.json
examples/shared-worker/rollup.config.js
examples/shared-worker/src/example-shared-worker.ts
examples/shared-worker/src/interfaces/IExampleMessage.ts
examples/shared-worker/src/worker-npm-init.ts
examples/shared-worker/src/worker.ts
examples/shared-worker/src/worker2.ts
examples/shared-worker/tsconfig.json
extensions/applicationinsights-analytics-js/src/JavaScriptSDK/Telemetry/PageViewManager.ts
extensions/applicationinsights-dependencies-js/src/ajax.ts
gruntfile.js
rush.json
shared/AppInsightsCore/src/JavaScriptSDK/InstrumentHooks.ts
tools/release-tools/setVersion.js

- Merge from `beta` [BUG] SharedWorker does not Instrument fetch correctly #1996
- [BUG] App Insights not auto-capturing from a Web Worker #1995

[Master] [BUG] SharedWorker does not Instrument fetch correctly #1996

---

AISKU/package.json
AISKULight/package.json
channels/applicationinsights-channel-js/Tests/Unit/src/Sender.tests.ts
channels/applicationinsights-channel-js/package.json
channels/applicationinsights-channel-js/src/Sender.ts
channels/tee-channel-js/package.json
common/Tests/Framework/src/AITestClass.ts
common/config/rush/npm-shrinkwrap.json
examples/AISKU/package.json
examples/dependency/package.json
examples/shared-worker/package.json
extensions/applicationinsights-analytics-js/package.json
extensions/applicationinsights-clickanalytics-js/package.json
extensions/applicationinsights-debugplugin-js/package.json
extensions/applicationinsights-dependencies-js/package.json
extensions/applicationinsights-perfmarkmeasure-js/package.json
extensions/applicationinsights-properties-js/package.json
shared/AppInsightsCommon/package.json
shared/AppInsightsCore/package.json
tools/applicationinsights-web-snippet/package.json
tools/chrome-debug-extension/package.json
tools/rollup-es5/README.md
tools/rollup-es5/Tests/Unit/src/Es5Rollup.Tests.ts
tools/rollup-es5/package.json
tools/rollup-es5/src/es5/Es5Tokens.ts
tools/shims/README.md
tools/shims/package.json

Cherry-picking #2036 from `master`
[Main] Rollup-ES5 Update readme and version to 1.0.1

[Main][BUG] Don't attempt to send message batch when known to be offline #2034 (#2036)

---

AISKU/Tests/es6-module-type-check/package.json
AISKU/Tests/es6-module-type-check/src/main.ts
AISKU/Tests/es6-module-type-check/tsconfig.json
AISKU/src/Initialization.ts
channels/applicationinsights-channel-js/src/EnvelopeCreator.ts
channels/applicationinsights-channel-js/src/Sender.ts
common/config/rush/npm-shrinkwrap.json
extensions/applicationinsights-analytics-js/src/JavaScriptSDK/AnalyticsPlugin.ts
extensions/applicationinsights-analytics-js/src/JavaScriptSDK/Telemetry/PageViewPerformanceManager.ts
extensions/applicationinsights-clickanalytics-js/Tests/Unit/src/ClickEventTest.ts
extensions/applicationinsights-clickanalytics-js/src/ClickAnalyticsPlugin.ts
extensions/applicationinsights-clickanalytics-js/src/common/Utils.ts
extensions/applicationinsights-properties-js/src/TelemetryContext.ts
rush.json
tools/release-tools/setVersion.js

[Master] Type 'T' does not satisfy the constraint 'IConfiguration' #2065
[Master] [BUG] ClickAnalytics throwing errors in console #2075

[Master] [BUG] The SDK is not limiting the sdkVersion length, which causes the nightly builds to throw error #2079

---

package.json
tools/status-tools/github-status.js
tools/status-tools/package.json

Adds a simple script that uses the GitHub CLI to report the status of all issues -- used for planning, no SDK functionality included.

Add Issue state reporting script

---

.github/workflows/ci.yml
.github/workflows/codeql-analysis.yml
channels/applicationinsights-channel-js/Tests/Unit/src/Sender.tests.ts
channels/applicationinsights-channel-js/src/Interfaces.ts
channels/applicationinsights-channel-js/src/Sender.ts

* fix sendbeacon sender
* update
Cherry-picked 71a33e834315b73e22af99183649c8a63646936a from `main`

[Main][Task]26079397: Add disableBeaconSplit sender config and fix potential duplicated events during unload/fallback sender (#2208)

---

AISKU/Tests/Unit/src/AISKUSize.Tests.ts
AISKULight/Tests/Unit/src/AISKULightSize.Tests.ts
README.md
channels/applicationinsights-channel-js/Tests/Unit/src/Sender.tests.ts
channels/applicationinsights-channel-js/src/Sender.ts

[release-3.0] Cherry-Pick: [Main][Task]26396663: Set default disableBeaconSplit to true (#2236)

---

AISKU/Tests/Unit/src/applicationinsights.e2e.tests.ts
common/config/rush/npm-shrinkwrap.json
shared/AppInsightsCommon/src/Telemetry/Exception.ts

for #2225 
id is casted when sending telemetry, hence put it inside properties field.

[main] #2225 pass customer exception id into telemetry

---

shared/1ds-core-js/src/Enums.ts

This adds two new enums values for PII Kind. One for IPv6 Address scrubbing, and one for dropping data.

Addng two new PII Kind values for IPv6 scrubbing and dropping data.

---

.github/workflows/ci.yml
.gitignore
common/config/rush/npm-shrinkwrap.json
examples/AISKU/package.json
examples/cfgSync/package.json
examples/dependency/package.json
examples/shared-worker/package.json
package.json
tools/chrome-debug-extension/manifest.json
tools/release-tools/npm_package.js
tools/release-tools/package_groups.json
tools/release-tools/setVersion.js

[cherrypick:main] remove node 14 (#2308)
[release-3.0] Update publishConfig to use release3

[Release-3.0][cherrypick:main] Internal Task: Update npm pack sequence (#2244)

---

AISKU/scripts/listAzCdnVersions.ps1
AISKU/scripts/publishAzReleaseToCdn.ps1
AISKU/scripts/setAzActiveCdnVersion.ps1
common/publish/AzStorageHelper/AzStorageHelper.psm1
extensions/applicationinsights-clickanalytics-js/scripts/listAzCdnVersions.ps1
extensions/applicationinsights-clickanalytics-js/scripts/publishAzReleaseToCdn.ps1
extensions/applicationinsights-clickanalytics-js/scripts/setAzActiveCdnVersion.ps1
extensions/applicationinsights-debugplugin-js/scripts/listAzCdnVersions.ps1
extensions/applicationinsights-debugplugin-js/scripts/publishAzReleaseToCdn.ps1
extensions/applicationinsights-debugplugin-js/scripts/setAzActiveCdnVersion.ps1
extensions/applicationinsights-perfmarkmeasure-js/scripts/listAzCdnVersions.ps1
extensions/applicationinsights-perfmarkmeasure-js/scripts/publishAzReleaseToCdn.ps1
extensions/applicationinsights-perfmarkmeasure-js/scripts/setAzActiveCdnVersion.ps1
tools/chrome-debug-extension/scripts/listAzCdnVersions.ps1
tools/chrome-debug-extension/scripts/publishAzReleaseToCdn.ps1
tools/chrome-debug-extension/scripts/setAzActiveCdnVersion.ps1
tools/config/scripts/listAzCdnVersions.ps1
tools/config/scripts/publishAzReleaseToCdn.ps1
tools/config/scripts/setAzActiveCdnVersion.ps1

- cherry-picked from main and verified locally

[Master] Publishing: Add support for Az Modules instead of AzureRM Modules

---

AISKU/package.json
AISKULight/package.json
channels/1ds-post-js/package.json
channels/applicationinsights-channel-js/package.json
channels/offline-channel-js/package.json
channels/tee-channel-js/package.json
common/Tests/Framework/package.json
common/config/rush/npm-shrinkwrap.json
common/scripts/install-run-rush.js
common/scripts/install-run-rushx.js
common/scripts/install-run.js
examples/AISKU/package.json
examples/cfgSync/package.json
examples/dependency/package.json
examples/shared-worker/package.json
extensions/applicationinsights-analytics-js/package.json
extensions/applicationinsights-cfgsync-js/package.json
extensions/applicationinsights-clickanalytics-js/package.json
extensions/applicationinsights-debugplugin-js/package.json
extensions/applicationinsights-dependencies-js/package.json
extensions/applicationinsights-osplugin-js/package.json
extensions/applicationinsights-perfmarkmeasure-js/package.json
extensions/applicationinsights-properties-js/package.json
package.json
rush.json
shared/1ds-core-js/package.json
shared/AppInsightsCommon/package.json
shared/AppInsightsCore/package.json
tools/chrome-debug-extension/package.json
tools/shims/package.json

Bump @nevware21/ts-utils from 0.11.1 to 0.11.3
Bump @nevware21/ts-async from 0.5.1 to 0.5.2

Bump @microsoft/rush from 5.97.1 to 5.129.6

---

tools/applicationinsights-web-snippet/Tests/manual/cspUseNounceTest.html
tools/applicationinsights-web-snippet/src/snippet.ts
tools/applicationinsights-web-snippet/src/type.ts
tools/applicationinsights-web-snippet/trustedTypeSupport.md

[main] Trusted Type Policy Support for nounce tag

---

README.md

First glance of the readme intro made me think this was for non-browser environments. I think it could be a little clearer.

Readme - Remove double negative

---

tools/applicationinsights-web-snippet/src/1dsSupport.ts
tools/applicationinsights-web-snippet/src/aiSupport.ts
tools/applicationinsights-web-snippet/src/snippet.ts

[main] snippet generation fix for pr #2428
