JavaScript/JavaScriptSDK.Tests/chutzpah.json
JavaScript/JavaScriptSDK/appInsights.ts

This fixes address two issues -
1. Fix the exception that was being thrown by the _onError function.
2. Temporary fix for running chutzpah tests. We can now run all the tests in one batch. We cannot run individual tests yet. We will be fixing that in a next update.

Fix for onError exceptions and temporary fix for chutzpah tests

---

JavaScript/JavaScriptSDK.Tests/CheckinTests/Util.tests.ts
JavaScript/JavaScriptSDK/Sender.ts
JavaScript/JavaScriptSDK/Util.ts
JavaScript/JavaScriptSDK/appInsights.ts

Because of CORS some users are getting "Script error." with no details (url/stack trace/file name). This is not actionable. In this fix "Script error." 's are filtered out.
For our own exceptions (coming from the script on CDN - ai.0.js) a tracing has been added to report meaningful errors when they happen. Otherwise we have the same "Script error." problem.

- Stop sending "Script error." - Adding try/catch blocks to public api

---

JavaScript/JavaScriptSDK.Tests/CheckinTests/Util.tests.ts
JavaScript/JavaScriptSDK/Util.ts
JavaScript/JavaScriptSDK/appInsights.ts

Based on telemetry looks like all problems currently come from our own script and I just wrapped all our code with try/catch which should give us real exceptions with details. Also the logic being removed is far from ideal because it works only for safari.

Remove logic of filtering out "Script error."

---

JavaScript/JavaScriptSDK/Telemetry/PageViewPerformance.ts
JavaScript/JavaScriptSDK/appInsights.ts

0 is considered invalid and shouldn't be reported. Otherwise it impacts aggregations shown in UI.

Don't send client perf events when total is 0; bump up sdk version

---

JavaScript/JavaScriptSDK.Tests/CheckinTests/Util.tests.ts
JavaScript/JavaScriptSDK/Telemetry/Exception.ts
JavaScript/JavaScriptSDK/Util.ts
JavaScript/JavaScriptSDK/appInsights.ts

There's not much we can do about "Script error" issue. It happens with the script from domain different from web page is throwing the error. In this case all data about the exception get's cleaned before we receive it.
The only reasonable fix is to provide a meaningful explanation to users.
We also used to show ai.0.js in file name which is incorrect - that was changed to "unknown"

Addressing "Script error" issue

---

JavaScript/JavaScriptSDK.Tests/CheckinTests/Util.tests.ts
JavaScript/JavaScriptSDK.Tests/CheckinTests/appInsights.tests.ts
JavaScript/JavaScriptSDK/Util.ts
JavaScript/JavaScriptSDK/appInsights.ts

This pull request attempts to improve diagnostics information we log in `AppInsithgs._onerror` method when encountering unexpected exceptions to help us understand the cause of the following error: 
```
AI (Internal): _onerror threw an exception: {} while logging error: null
```
In addition to dumping the names and the properties of the unexpected exception, the `_onerror` method now also writes `toString` representation of the exception object.

Improve diagnostics of unexpected exceptions in AppInsights._onerror

---

JavaScript/Microsoft.ApplicationInsights.JavaScript.sln
README.md
RunTestsInBrowser.ps1

This removes the need to setup the Selenium folder as an app in local IIS.

Add RunTestsInBrowser.ps1 script for running check-in tests in a browser

---

JavaScript/JavaScriptSDK.Tests/CheckinTests/Telemetry/PageViewPerformance.tests.ts
JavaScript/JavaScriptSDK/Telemetry/PageViewPerformance.ts

Some modern browsers (specifically Chrome, but  sometimes IE 10 too) issues domLoading event before responseEnd event, so responseStart->responseEnd interval overlaps with domLoading->loadEventEnd interval causing subcomponent times to be larger than navigationStart->loadEventEnd total, causing user confusion when they look in the UI. To account for this situation I'm changing the measurement of domProcessing  interval to start with responseEnd event.

Measuring domProcessing from responseEnd

---

JavaScript/JavaScriptSDK.Tests/E2ETests/PublicApiTests.ts
JavaScript/JavaScriptSDK.Tests/TestFramework/PollingAssert.ts
JavaScript/JavaScriptSDK.Tests/TestFramework/TestClass.ts

This is an extension of the fix I made recently: https://github.com/Microsoft/ApplicationInsights-JS/commit/23674bddde2cc42d1031746ea030f6a3681cb55a
Polling assert is a new kind of assert that:
- executes asyncronously (by timeout) for a specific amount of time (rather than loop cycles)
- stops other test steps from executing
- takes a callback to the next test step to execute after if finishes itself
The disclaimer is that we're going to do incremental improvements - need to apply this patter across other tests.

Polling assert

---

JavaScript/JavaScriptSDK.Tests/CheckinTests/Context/Session.tests.ts
JavaScript/JavaScriptSDK.Tests/CheckinTests/Initialization.tests.ts
JavaScript/JavaScriptSDK.Tests/CheckinTests/Util.tests.ts
JavaScript/JavaScriptSDK.Tests/CheckinTests/appInsights.tests.ts
JavaScript/JavaScriptSDK/Context/Session.ts
JavaScript/JavaScriptSDK/Context/User.ts
JavaScript/JavaScriptSDK/Init.ts
JavaScript/JavaScriptSDK/Initialization.ts
JavaScript/JavaScriptSDK/Util.ts

These changes fix a bug where we incorrectly send the wrong session id on the first request after a session has expired due to the session cookie persisting for a very long time. 
Most of the additions are to fix a bug that pops up after expiring the session cookie where we need to keep the old session id to terminate the session.

Fix bug with sending expired session ids

---

JavaScript/JavaScriptSDK.Tests/CheckinTests/Telemetry/PageViewPerformance.tests.ts
JavaScript/JavaScriptSDK.Tests/CheckinTests/appInsights.tests.ts
JavaScript/JavaScriptSDK/Telemetry/PageViewPerformance.ts
JavaScript/JavaScriptSDK/appInsights.ts

PageView used to be sent synchronously when user does trackPageView(). Now we're changing it to send together with client perf (when page is loaded), i.e. asynchronously. This required changing/refactoring lots of tests.

Send PageViews together with client perf And refactored unit tests

---

JavaScript/JavaScriptSDK/Context/Session.ts
JavaScript/JavaScriptSDK/Util.ts

Our telemetry has shown local storage support to be quite good. These logs can be quieted down a bit.
Also make the recently added session storage logging distinct from local storage logging.

Move local storage logging severity from CRITICAL to WARNING. 

---

JavaScript/JavaScriptSDK.Tests/CheckinTests/Initialization.tests.ts
JavaScript/JavaScriptSDK.Tests/CheckinTests/TelemetryContext.tests.ts
JavaScript/JavaScriptSDK.Tests/CheckinTests/appInsights.tests.ts
JavaScript/JavaScriptSDK.Tests/Selenium/Tests.html
JavaScript/JavaScriptSDK/Telemetry/PageView.ts
JavaScript/JavaScriptSDK/Telemetry/PageViewPerformance.ts
JavaScript/JavaScriptSDK/TelemetryContext.ts
JavaScript/JavaScriptSDK/appInsights.ts

Implementation of Telemtry initializer concept - allows to attach properties and measurements to all telemetry items.
Suggested use:
1) with snippet config
<SNIPPET>
}({
instrumentationKey: "b9d56dad-4148-458d-8dd1-147c61a17b07",
properties: { prop1: "val1", prop2: "val2" },
measurements: { m1: 100, m2: 200 }
});
window.appInsights = appInsights;        
appInsights.trackPageView();
2) with queue push (if can't use option 1)
appInsights.queue.push(function() { 
appInsights.context.properties = {prop1: "val1", prop2: "val2"}
appInsights.context.measurements = {m1: 100, m2: 200}
});
Next steps - stop needing queue.push (though reading appInsights.properties in initialization)

Telemetry initializer

---

JavaScript/JavaScriptSDK/Init.ts
JavaScript/JavaScriptSDK/Logging.ts
JavaScript/JavaScriptSDK/Util.ts

With reference to error - AI (Internal): trackPageView failed on page load calculation: [object Error]{ stack: 'undefined', message: ''console' is undefined'.
We are using console.warn directly in two places and console.error in one which will throw errors in case that the "console" object is undefined (as the error above suggests.) In this pull request, we are switching to use the Util console warn func which checks for the presence of the console object and its funcs before using them.

Changing console references to use Util console warn function

---

JavaScript/JavaScriptSDK.Tests/CheckinTests/Telemetry/Exception.tests.ts
JavaScript/JavaScriptSDK/Telemetry/Exception.ts

The following unhandled exception was reported 671 times by internal AI JS SDK telemetry during the week of 8/16, affecting 24 applications:
```
AI (Internal): _onerror threw [object Error]{ 
stack: 'TypeError: Cannot set property 'assembly' of undefined    
at <error: TypeError: undefined is not a function>     
at <error: TypeError: undefined is not a function>     
at <error: TypeError: undefined is not a function>     
at <error: TypeError: undefined is not a function>', 
message: 'Cannot set property 'assembly' of undefined', 
name: 'TypeError' while logging error, error will not be collected: null
```
I believe it is caused by a problem in the `Exception.CreateSimpleException` method, which is called by `SendCORSException` called from `_onerror`. The current code in …

Fix "Cannot set property 'assembly' of undefined" error in CreateSimpleException 

---

JavaScript/JavaScriptSDK.Tests/CheckinTests/Initialization.tests.ts
JavaScript/JavaScriptSDK.Tests/CheckinTests/Telemetry/PageViewPerformance.tests.ts
JavaScript/JavaScriptSDK.Tests/CheckinTests/appInsights.tests.ts
JavaScript/JavaScriptSDK/Telemetry/PageViewPerformance.ts
JavaScript/JavaScriptSDK/appInsights.ts

1) Default scenario: forcing PageView duration being page load time (equal to PageViewPerformance.total).
This will be the default behavior. 
2) If new config parameter ('relativePageViewDuration') is set to true than page view duration will equal to the time from window.performance.timing.navigationStart to the moment of calling the trackPageView(). This is useful when page view duration has a special meaning and is not bound to "physical" page load time. For example, if a page has many ajax calls which execute after DOM and all resources are loaded, and we consider the last ajax call as the end of page load.

By default page view duration equals Page load time 

---

JavaScript/JavaScriptSDK/Context/Operation.ts

This change will allow to glue page view and page view performance documents in the UI. So that we can show a blade filtered by operation name and showing data of both doc types (raw grid with page views and performance stacked area chart based on page view performance)

Setting operation name to window.location.pathname

---

JavaScript/JavaScriptSDK.Tests/CheckinTests/Sender.tests.ts
JavaScript/JavaScriptSDK.Tests/CheckinTests/Serializer.tests.ts
JavaScript/JavaScriptSDK.Tests/CheckinTests/Telemetry/PageViewPerformance.tests.ts
JavaScript/JavaScriptSDK.Tests/CheckinTests/appInsights.tests.ts
JavaScript/JavaScriptSDK.Tests/TestFramework/ContractTestHelper.ts
JavaScript/JavaScriptSDK/Serializer.ts
JavaScript/JavaScriptSDK/Telemetry/Common/Data.ts
JavaScript/JavaScriptSDK/Telemetry/Common/DataPoint.ts
JavaScript/JavaScriptSDK/Telemetry/Common/Envelope.ts
JavaScript/JavaScriptSDK/Telemetry/Event.ts
JavaScript/JavaScriptSDK/Telemetry/Exception.ts
JavaScript/JavaScriptSDK/Telemetry/Metric.ts
JavaScript/JavaScriptSDK/Telemetry/PageView.ts
JavaScript/JavaScriptSDK/Telemetry/PageViewPerformance.ts
JavaScript/JavaScriptSDK/Telemetry/RemoteDependencyData.ts
JavaScript/JavaScriptSDK/Telemetry/SessionTelemetry.ts
JavaScript/JavaScriptSDK/Telemetry/Trace.ts
JavaScript/JavaScriptSDK/ajax/ajax.ts

* Refactor aiDataContract object to use enum instead of bool 
* User can use functions in aiDataContract (see Envelope.ts)
* User can mark a fields as hidden an it will not be serialized

Do not send sampleRate when it is 100 #74

---

JavaScript/JavaScriptSDK.Tests/CheckinTests/appInsights.tests.ts
JavaScript/JavaScriptSDK/Telemetry/PageViewPerformance.ts
JavaScript/JavaScriptSDK/appInsights.ts
JavaScript/JavaScriptSDK/snippet.js

We don't want to lose page views when navigation timing is not supported by browsers (3% of cases).
However since duration property is mandatory we have no choice but setting it to 0.

PageView: sending 0 duration when duration is unknown

---

JavaScript/JavaScriptSDK/Logging.ts
JavaScript/JavaScriptSDK/Telemetry/PageViewManager.ts
JavaScript/JavaScriptSDK/Telemetry/PageViewPerformance.ts

This means they won't be sent to customer ikey as trace messages and instead will just appear in browser console. These are non-actionable errors for the ikey owner as we know that certain browser either don't support or incorrectly implement page performance API. This is to address #99

Making messages reporting incorrect page performance warning-only

---

JavaScript/JavaScriptSDK.Tests/CheckinTests/Context/Sample.tests.ts
JavaScript/JavaScriptSDK.Tests/CheckinTests/Context/Session.tests.ts
JavaScript/JavaScriptSDK.Tests/CheckinTests/Context/User.tests.ts
JavaScript/JavaScriptSDK.Tests/CheckinTests/Initialization.tests.ts
JavaScript/JavaScriptSDK.Tests/CheckinTests/Logging.tests.ts
JavaScript/JavaScriptSDK.Tests/CheckinTests/PageVisitTimeManager.tests.ts
JavaScript/JavaScriptSDK.Tests/CheckinTests/Sender.tests.ts
JavaScript/JavaScriptSDK.Tests/CheckinTests/Serializer.tests.ts
JavaScript/JavaScriptSDK.Tests/CheckinTests/Telemetry/PageViewPerformance.tests.ts
JavaScript/JavaScriptSDK.Tests/CheckinTests/TelemetryContext.tests.ts
JavaScript/JavaScriptSDK.Tests/CheckinTests/Util.tests.ts
JavaScript/JavaScriptSDK.Tests/CheckinTests/ajax.tests.ts
JavaScript/JavaScriptSDK.Tests/CheckinTests/appInsights.tests.ts
JavaScript/JavaScriptSDK.Tests/E2ETests/DisableTelemetryTests.ts
JavaScript/JavaScriptSDK.Tests/E2ETests/PublicApiTests.ts
JavaScript/JavaScriptSDK.Tests/E2ETests/SanitizerE2E.tests.ts
JavaScript/JavaScriptSDK.Tests/E2ETests/autoCollection.tests.ts
JavaScript/JavaScriptSDK.Tests/E2ETests/snippet.tests.ts
JavaScript/JavaScriptSDK.Tests/Performance/pageLoad.perftests.ts

In this change I made sure we create spies/stubs/mocks via 'this.sandbox'. This allows to skip manual .restore() and reduces bugs because of missed restore (and simplifies the code for future tests).

Refactor tests

---

JavaScript/JavaScriptSDK.Tests/CheckinTests/ajax.tests.ts
JavaScript/JavaScriptSDK/ajax/ajaxUtils.ts

Per http://stackoverflow.com/questions/313893/how-to-measure-time-taken-by-a-function-to-execute 
Our telemetry indicates that ajax start time sometimes is bigger than finish time.

switching to performance.now() for ajax timing

---

JavaScript/JavaScriptSDK.Tests/CheckinTests/Initialization.tests.ts
JavaScript/JavaScriptSDK.Tests/CheckinTests/appInsights.tests.ts
JavaScript/JavaScriptSDK/AppInsights.ts
JavaScript/JavaScriptSDK/Initialization.ts

75th percentile of our users have 15 ajaxes per page view. To prevent quota cap setting limit of ajaxes per view to 20.

Ajax - client side throttling per view

---

JavaScript/JavaScriptSDK/Telemetry/PageViewManager.ts

Overriding duration with a duration of 0 will send page view with duration 0 now instead of the value of customDuration.

Fix allows user to submit 0 custom duration

---

bower.json

It's common practice for third party tools to use the main object in bower.json to detect which are the distribution files. 
I encountered an issue where WireDep was not recognizing AppInsights #127, this fixes the problem.

adding main to bower.json to help bower tools

---

JavaScript/JavaScriptSDK.Tests/CheckinTests/Initialization.tests.ts
JavaScript/JavaScriptSDK.Tests/CheckinTests/Telemetry/Exception.tests.ts
JavaScript/JavaScriptSDK.Tests/CheckinTests/appInsights.tests.ts
JavaScript/JavaScriptSDK/AppInsights.ts
JavaScript/JavaScriptSDK/Initialization.ts
JavaScript/JavaScriptSDK/Telemetry/Exception.ts

Our backend rejects empty methods on exception stack.

Set exception method to "<no_method>" if it's empty

---

JavaScript/JavaScriptSDK.Tests/CheckinTests/Initialization.tests.ts
JavaScript/JavaScriptSDK.Tests/CheckinTests/appInsights.tests.ts
JavaScript/JavaScriptSDK/AppInsights.ts
JavaScript/JavaScriptSDK/Initialization.ts

Disables housekeeping in window.onBeforeUnload. In some cases IE throws an error when you try to send ajax request on beforeunload. The flag 'disableFlushOnBeforeUnload' is intended to help users cope with errors they get in this case.

Switch to disable 'house keeping'

---

JavaScript/JavaScriptSDK/Util.ts

Calling createElement() on an empty object causes an exception, instead check if document.createElement is defined

Fix a crash in UrlHelper if document isn't defined

---

JavaScript/JavaScriptSDK.Tests/CheckinTests/Telemetry/RemoteDependency.tests.ts
JavaScript/JavaScriptSDK.Tests/CheckinTests/appInsights.tests.ts
JavaScript/JavaScriptSDK/AppInsights.ts
JavaScript/JavaScriptSDK/Telemetry/RemoteDependencyData.ts
JavaScript/JavaScriptSDK/ajax/ajax.ts

The `trackAjax` function is public so I added `method` (verb) as an optional parameter. This way it won't affect existing customer. If the value is null only the absolute URL will be used. 
The verb isn't exposed in the UI yet, but it is accessible through Application Analytic.

Log verb as part of dependency name

---

JavaScript/JavaScriptSDK.Tests/CheckinTests/Telemetry/DataSanitizer.tests.ts
JavaScript/JavaScriptSDK/Telemetry/Common/Envelope.ts
JavaScript/JavaScriptSDK/Telemetry/Event.ts
JavaScript/JavaScriptSDK/Telemetry/Exception.ts
JavaScript/JavaScriptSDK/Telemetry/Metric.ts
JavaScript/JavaScriptSDK/Telemetry/PageView.ts
JavaScript/JavaScriptSDK/Telemetry/PageViewPerformance.ts

#184. If name is required set the value to 'not_specified' if value is null or empty. 
Common.DataSanitizer.sanitizeString(exception.name || Util.NotSpecified) didn't handle " " names correctly. It will return 'not_specified' with the fix.

Required field is set to not_specified if value is missing

---

JavaScript/JavaScriptSDK.Tests/JavaScriptSDK.Tests.csproj
JavaScript/JavaScriptSDK.Tests/packages.config
JavaScript/JavaScriptSDK/JavaScriptSDK.csproj

* JavaScriptSDK.Tests project is referencing tsc in Exec tasks, assuming it is available in PATH (which it is not, unless installed on the box). I'm referencing TS compiler package and referencing it from packages path
* Removing hardcoded VS version, so that solution can be opened and built with VS2015

Reference TS compiler in tests, removing hardcoded VS version

---

JavaScript/JavaScriptSDK.Tests/CheckinTests/Util.tests.ts
JavaScript/JavaScriptSDK/Logging.ts
JavaScript/JavaScriptSDK/Util.ts
JavaScript/JavaScriptSDK/snippet.js

This fixes #249 
I still need to do some testing to validate the SDK works as expected in the `document.cookie` is not accessible. Ideally it should still send all telemetry, but without session and user id.

Check if document.cookie is available

---

JavaScript/JavaScriptSDK/SendBuffer.ts

If the back-end is not responding or is responding very slow, the SENT_BUFFER can grow above the max buffer size limit. This can cause a situation when the restored buffer has more than MAX_BUFFER_SIZE elements.

Sent buffer overflow

---

JavaScript/JavaScriptSDK/Initialization.ts
JavaScript/JavaScriptSDK/Sender.ts

Extra code for XDomainRequests is required because IE8,9 requires the same schema [see point 7 here](https://blogs.msdn.microsoft.com/ieinternals/2010/05/13/xdomainrequest-restrictions-limitations-and-workarounds/)
Fixes: #93

Send telemetry over HTTPS

---

JavaScript/JavaScriptSDK.Tests/E2ETests/PostBuild.ps1

Create E2ETests as a directory instead of a file by appending '\' to the route.

Create E2ETests as a directory.

---

JavaScript/JavaScriptSDK.Tests/CheckinTests/Logging.tests.ts
JavaScript/JavaScriptSDK.Tests/CheckinTests/Sender.tests.ts
JavaScript/JavaScriptSDK/Logging.ts

* Limit console logging to only one message of a given type (if !verboseLogging)
* Limit to only one internal message log per page view when the session storage is not available

Do not flood the console!

---

JavaScript/JavaScriptSDK.Tests/CheckinTests/Sender.tests.ts
JavaScript/JavaScriptSDK/Sender.ts
JavaScript/JavaScriptSDK/Telemetry/Common/Envelope.ts
JavaScript/JavaScriptSDK/Telemetry/Event.ts
JavaScript/JavaScriptSDK/Telemetry/Exception.ts
JavaScript/JavaScriptSDK/Telemetry/Metric.ts
JavaScript/JavaScriptSDK/Telemetry/PageView.ts
JavaScript/JavaScriptSDK/Telemetry/PerformanceAnalyzer.ts

XDomainRequest requires the same protocol as the hosting page. If the protocol doesn't match, we can't send the telemetry :(
Fixes #314

XDomain sender should drop the telemetry if the Endpoint protocol and the hosting page protocol don't match

---

JavaScript/JavaScriptSDK.Tests/Selenium/Tests.cs

It will speed up test execution.

Log additional test logs only when there is at least one failure

---

JavaScript/JavaScriptSDK.Tests/Selenium/Tests.cs

I've noticed that our tests are more reliable when executed in Chrome.

Run unit tests in Chrome

---

JavaScript/JavaScriptSDK.Tests/CheckinTests/Sender.tests.ts

This is a temporary change to reduce the size of the JS SDK. I'll refactor DataLossAnalyzer code soon - #208.

Disable DataLossAnalyzer unit tests

---

JavaScript/JavaScriptSDK.Module/AppInsightsModule.ts
JavaScript/JavaScriptSDK.Tests/E2ETests/snippet.tests.ts
JavaScript/JavaScriptSDK/snippet.js

Fixes #282. 
* capture errors when they are thrown from the snippet script block
* wrap the correct `onerror` method in AppInsightsModule.ts
* add end-to-end unit test

Capture errors thrown from the snippet script block

---

JavaScript/JavaScriptSDK.Interfaces/IAppInsights.ts
JavaScript/JavaScriptSDK/AppInsights.ts
JavaScript/JavaScriptSDK/Telemetry/Trace.ts
JavaScript/JavaScriptSDK/Util.ts

Don't know how to change and run the automated test. Tested manually.

Added Severity level to tracing

---

JavaScript/JavaScriptSDK/Telemetry/Trace.ts

`MessageData` doesn't have a measurements field. Ref[MessageData schema](https://github.com/Microsoft/ApplicationInsights-Home/blob/master/EndpointSpecs/Schemas/Docs/MessageData.md)

Remove measurements field from MessageData

---

JavaScript/JavaScriptSDK.Tests/CheckinTests/Context/HashCodeScoreGenerator.tests.ts
JavaScript/JavaScriptSDK.Tests/CheckinTests/Sender.tests.ts
JavaScript/JavaScriptSDK.Tests/CheckinTests/Serializer.tests.ts
JavaScript/JavaScriptSDK.Tests/CheckinTests/Telemetry/DataSanitizer.tests.ts
JavaScript/JavaScriptSDK.Tests/CheckinTests/TelemetryContext.tests.ts
JavaScript/JavaScriptSDK.Tests/TestFramework/ContractTestHelper.ts
JavaScript/JavaScriptSDK/AppInsights.ts
JavaScript/JavaScriptSDK/Context/Operation.ts
JavaScript/JavaScriptSDK/Context/Session.ts
JavaScript/JavaScriptSDK/Context/User.ts
JavaScript/JavaScriptSDK/Init.ts
JavaScript/JavaScriptSDK/Initialization.ts
JavaScript/JavaScriptSDK/JavaScriptSDK.csproj
JavaScript/JavaScriptSDK/SendBuffer.ts
JavaScript/JavaScriptSDK/Sender.ts
JavaScript/JavaScriptSDK/Serializer.ts
JavaScript/JavaScriptSDK/Telemetry/Common/DataSanitizer.ts
JavaScript/JavaScriptSDK/TelemetryContext.ts
JavaScript/JavaScriptSDK/Util.ts
JavaScript/JavaScriptSDK/ajax/ajax.ts
JavaScript/JavaScriptSDK/ajax/ajaxRecord.ts
JavaScript/JavaScriptSDK/ajax/ajaxUtils.ts
JavaScript/JavaScriptSDK/packages.config

This PR fixes source maps in the un-minified `ai.js` file. I'll add source maps to minified library in a next pull request.
Changes: 
* fix import path
* point to typescript source files in source maps (TypeScriptSourceRoot)

Add source maps to un-minified library (ai.js)

---

JavaScript/JavaScriptSDK/JavaScriptSDK.csproj

Fixing `Build: Option 'inlineSources' can only be used when either option '--inlineSourceMap' or option '--sourceMap' is provided.` build error.

Fix build break

---

API-reference.md
JavaScript/JavaScriptSDK.Interfaces/Telemetry/IEnvelope.ts
JavaScript/JavaScriptSDK/TelemetryContext.ts

Fix telemetry context function type

---

JavaScript/JavaScriptSDK.Tests/CheckinTests/Sender.tests.ts
JavaScript/JavaScriptSDK/Sender.ts

With this change, the SDK will log the response code (status) in request `onError` handler.

Log the response code (status) in request onError handler

---

.gitignore
JavaScript/JavaScriptSDK.Interfaces/IAppInsights.ts
JavaScript/JavaScriptSDK/AppInsights.ts
JavaScript/JavaScriptSDK/Sender.ts

Allows the flush method exposed via the SDK to be called with an optional parameter to perform the flush synchronously.

Allow flush to be sync

---

API-reference.md

Fixed typo in comment from enableSessionStorageBuffer: resotered -> restored

fix typo on API-reference.md

---

JavaScript/JavaScriptSDK.Module/AppInsightsModule.ts

Fixes #387 
When using the library in a server-rendered scenario (ie: angular universal), even when you conditionally wrap the code to make sure it only is ran in an `isPlatformBrowser()` scenario, the `get appInsightsInstance` is still packaged into the server bundle, and errors out due window being used (when it doesn't exist).
This allows a server bundle to continue rendering without errors, and then the client-side JS code can run and connect to Application Insights.
cc/ @KamilSzostak 
--- 
Repro case here (sort of involved as it's an aspnetcore + angular + SSR solution similar to JavaScriptServices)
https://github.com/MarkPieszak/aspnetcore-angular2-universal/tree/app-insights-ssr-bug
An unhandled exception occurred while processing the request.
> Exception: Call to Node module …

bug(AppInsightsModule): fix window issue during server renders

---

Global.props
JavaScript/JavaScriptSDK/AppInsights.ts
bower.json
package.json

A new version is required to publish a fixed npm package. See #488.

version update 1.0.10 -> 1.0.11

---

JavaScript/JavaScriptSDK/AppInsights.ts

Piyali and I started separate conversation with Kusto team about only this particular field and they haven't replied to us for the past two weeks. So, we decided to release without this change then bring it back and immediately deploy to AIMon with it to see how it's going.

temporarily remove pageview.id initialization

---

JavaScript/JavaScriptSDK/Initialization.ts

Disable correlation header in request as it can potentially cause dependencies to fail when pre-flight response does not have requested header

Disable correlation header in request as it can potentially cause dependencies to fail when pre-flight response does not have requested header

---

JavaScript/JavaScriptSDK/ajax/fetch.ts

The issue with the fetch api instrumentation is that fetch api is based on promise and there is no support for promise in older versions of some browsers. While the code is not run in old versions, script load is failing. This may be due to promise chain syntax that we had. so, taking that out and replacing with alternate syntax.
I still think this won't work, as I'm seeing another script error, much earlier in the script though.
Need to test this out some more. We may need to take out fetch support altogether if this doesnt work.

Remove promise chaining syntax

---

AISKU/Tests/ApplicationInsightsDeprecatedTests.ts
AISKU/Tests/Selenium/appinsights-sdk.tests.ts
AISKU/src/ApplicationInsightsContainer.ts
AISKU/src/ApplicationInsightsDeprecated.ts
AISKU/src/Init.ts
AISKU/src/Initialization.ts
AISKU/src/applicationinsights-web.ts
ApplicationInsights/package.json
ApplicationInsights/src/JavaScriptSDK/ApplicationInsights.ts

This provides an easy mechanism for customers to try out new SDK bits without changing their instrumentation code.
- Will add more test cases
- need to also add support for context.addTelemetryInitializer

Add support to allow customers to reference new CDN with config parameter that provides deprecated api support.

---

.gitignore
AISKU/legacy-readme.txt
AISKU/src/ApplicationInsightsContainer.ts
AISKU/src/ApplicationInsightsDeprecated.ts
AISKU/src/Init.ts
AISKU/src/Initialization.ts
AppInsightsCommon/src/Interfaces/IConfig.ts
ApplicationInsights/src/JavaScriptSDK/ApplicationInsights.ts
extensions/applicationinsights-properties-js/src/Interfaces/ITelemetryConfig.ts
extensions/applicationinsights-properties-js/src/PropertiesPlugin.ts

- Remove ability (throw error) to add custom extensions when running in legacy code.
- Code clean up for old settings (unused).
- Hook up start/stop trackEvent for legacy apis.

Fixes from testing bridging functionality for existing PROD sdk 

---

AISKU/package.json
AISKU/src/ApplicationInsightsContainer.ts
AISKU/src/ApplicationInsightsDeprecated.ts
AISKU/src/Init.ts
AISKU/src/Initialization.ts
AISKULight/package.json
API-reference.md
AppInsightsCommon/package.json
AppInsightsCommon/src/TelemetryItemCreator.ts
ApplicationInsights/Tests/ApplicationInsights.tests.ts
ApplicationInsights/package.json
ApplicationInsights/src/JavaScriptSDK/ApplicationInsights.ts
extensions/applicationinsights-dependencies-js/Tests/Selenium/ajax.tests.ts
extensions/applicationinsights-dependencies-js/package.json
extensions/applicationinsights-dependencies-js/src/ajax.ts
extensions/applicationinsights-properties-js/package.json

- rename `timestamp` to `time`
- rename `instrumentationKey` to `ikey`
- Add request-context field to autocollected fetch requests when `enableCorsCorrelation` is enabled
- In initialization, make `queue`, `version` optional
- rework ordering of `loadAppInsights` call to ensure preinstrumentation autocollection works
- re-enable disabled ajax plugin tests

Release 1.0.0-beta.11

---

AISKULight/index.ts

When creating part B for track api, it is useful for user to view types that are supported.

Export types for part B in light sku

---

ApplicationInsights/src/JavaScriptSDK/ApplicationInsights.ts

Fixes #772 
Requires removal of `new Exception(...)` from Channel

create correct Exception baseData in ITelemetryItem before passing along

---

vNext/channels/applicationinsights-channel-js/Tests/Sender.tests.ts
vNext/channels/applicationinsights-channel-js/src/EnvelopeCreator.ts
vNext/channels/applicationinsights-channel-js/src/Sender.ts
vNext/shared/AppInsightsCore/src/JavaScriptSDK.Interfaces/IConfiguration.ts
vNext/shared/AppInsightsCore/src/JavaScriptSDK.Tests/Selenium/ApplicationInsightsCore.Tests.ts
vNext/shared/AppInsightsCore/src/JavaScriptSDK/AppInsightsCore.ts

Allow channel configuration to be passed in only through config.channels parameter. Disallow through config.extensions parameter, add unit tests. Fixes bug with multiple items being sent in telemetry in fabrikam.

Bug fix for duplicate telemetry issue in vNext ( 4088796)

---

vNext/extensions/applicationinsights-properties-js/src/Context/Session.ts
vNext/extensions/applicationinsights-properties-js/src/applicationinsights-properties-js.ts
vNext/shared/AppInsightsCommon/src/Interfaces/Context/ISession.ts

For extending properties plugin, interfaces fields should be optional.

properties plugin: export Session, make interface fields optional

---

JavaScript/JavaScriptSDK.Tests/E2ETests/SanitizerE2E.tests.ts
JavaScript/JavaScriptSDK.Tests/E2ETests/ValidateApi.tests.ts
JavaScript/JavaScriptSDK.Tests/E2ETests/snippet.tests.ts
vNext/AISKU/Tests/applicationinsights.e2e.tests.ts
vNext/AISKU/Tests/sanitizer.e2e.tests.ts
vNext/AISKU/Tests/sender.e2e.tests.ts
vNext/AISKU/Tests/validate.e2e.tests.ts
vNext/AISKU/package.json
vNext/AISKULight/package.json
vNext/channels/applicationinsights-channel-js/package.json
vNext/common/config/rush/npm-shrinkwrap.json
vNext/extensions/applicationinsights-analytics-js/package.json
vNext/extensions/applicationinsights-analytics-js/src/JavaScriptSDK/ApplicationInsights.ts
vNext/extensions/applicationinsights-dependencies-js/package.json
vNext/extensions/applicationinsights-properties-js/package.json
vNext/extensions/applicationinsights-react-native/package.json
vNext/shared/AppInsightsCommon/package.json
vNext/shared/AppInsightsCommon/src/Interfaces/IDependencyTelemetry.ts
vNext/shared/AppInsightsCommon/src/Interfaces/IEventTelemetry.ts
vNext/shared/AppInsightsCommon/src/Interfaces/IExceptionTelemetry.ts
vNext/shared/AppInsightsCommon/src/Interfaces/IMetricTelemetry.ts
vNext/shared/AppInsightsCommon/src/Interfaces/IPageViewPerformanceTelemetry.ts
vNext/shared/AppInsightsCommon/src/Interfaces/IPageViewTelemetry.ts
vNext/shared/AppInsightsCommon/src/Interfaces/ITraceTelemetry.ts
vNext/shared/AppInsightsCommon/src/Telemetry/Common/DataSanitizer.ts
vNext/shared/AppInsightsCore/package.json

- #816 - Rename measurement fields to accept a number
- #818 - Adds `refUri` from `document.referral` on pageview
- **Stringifies** part C objects so user provided custom `properties` objects will now show up properly in Azure
- **Travis CI:** Also fixes Travis CI tests sometimes failing by letting tests poll for longer.

stringify part c properties, add refUri

---

vNext/channels/applicationinsights-channel-js/src/EnvelopeCreator.ts
vNext/extensions/applicationinsights-analytics-js/src/JavaScriptSDK/ApplicationInsights.ts

Move `new Exception` to channel so that `aiDataContract` does not show up in `ITelemetryItem`

move exception creation to channel

---

vNext/AISKU/src/Initialization.ts
vNext/extensions/applicationinsights-analytics-js/Tests/ApplicationInsights.tests.ts
vNext/extensions/applicationinsights-analytics-js/src/JavaScriptSDK/ApplicationInsights.ts

Add missing initialization for `autoTrackPageVisitTime`
- Fixes #826

analytics: initialize autoTrackPageVisitTime deps

---

vNext/channels/applicationinsights-channel-js/Tests/Sender.tests.ts
vNext/channels/applicationinsights-channel-js/src/EnvelopeCreator.ts
vNext/extensions/applicationinsights-analytics-js/src/JavaScriptSDK/ApplicationInsights.ts

pageViewData: check for duration in part C data

---

vNext/extensions/applicationinsights-properties-js/src/Interfaces/ITelemetryConfig.ts
vNext/extensions/applicationinsights-properties-js/src/PropertiesPlugin.ts
vNext/shared/AppInsightsCommon/src/Util.ts
vNext/shared/AppInsightsCore/src/JavaScriptSDK/AppInsightsCore.ts
vNext/shared/AppInsightsCore/src/JavaScriptSDK/CoreUtils.ts

- Add `isCookieUseDisabled` to properties plugin for cases where analytics plugin is not available.

add isCookieUseDisabled to CoreUtils

---

vNext/channels/applicationinsights-channel-js/Tests/Sender.tests.ts
vNext/channels/applicationinsights-channel-js/src/EnvelopeCreator.ts
vNext/extensions/applicationinsights-properties-js/Tests/Selenium/properties.tests.ts

- Add missing `ext.device.deviceClass` lookup in channel: `EnvelopeCreator.ts` to add the item to `tags[CtxTagKeys.deviceType]`
- Re-enables disabled tests for this functionality in channel
- Add tests for adding this to `ITelemetryItem` in properties plugin
Addresses #843 and #835

channel: add missing deviceClass lookup to env

---

vNext/channels/applicationinsights-channel-js/Tests/Sender.tests.ts
vNext/channels/applicationinsights-channel-js/src/EnvelopeCreator.ts
vNext/extensions/applicationinsights-analytics-js/src/JavaScriptSDK/ApplicationInsights.ts
vNext/shared/AppInsightsCommon/Tests/Exception.tests.ts
vNext/shared/AppInsightsCommon/Tests/Selenium/appinsights-common.tests.ts
vNext/shared/AppInsightsCommon/src/Interfaces/IExceptionTelemetry.ts
vNext/shared/AppInsightsCommon/src/Telemetry/Exception.ts
vNext/shared/AppInsightsCommon/src/applicationinsights-common.ts

Adds `CreateFromInterface` static method and `toInterface` instance method. When converting back and fourth with these, result is equivalent. Interface mode only contains valid Part B.

common: add exception convert to/from interface

---

API-reference.md
API.md
JavaScript/JavaScriptSDK.Interfaces/Contracts/Generated/ContextTagKeys.ts
JavaScript/JavaScriptSDK.Tests/DefinitionTypes/applicationinsights-js-tests.ts
JavaScript/JavaScriptSDK.Tests/Selenium/ai.tests.d.ts
README.md
bower.json
legacy_README.md
package.json
vNext/AISKU/API.md
vNext/AISKU/README.md
vNext/AISKU/package-lock.json
vNext/AISKU/package.json
vNext/AISKULight/README.md
vNext/channels/applicationinsights-channel-js/README.md
vNext/extensions/applicationinsights-analytics-js/README.md
vNext/extensions/applicationinsights-analytics-js/package.json
vNext/extensions/applicationinsights-dependencies-js/README.md
vNext/extensions/applicationinsights-dependencies-js/package.json
vNext/extensions/applicationinsights-properties-js/README.md
vNext/extensions/applicationinsights-properties-js/package.json
vNext/extensions/applicationinsights-react-js/README.md
vNext/extensions/applicationinsights-react-js/package.json
vNext/extensions/applicationinsights-react-native/package.json
vNext/shared/AppInsightsCommon/README.md
vNext/shared/AppInsightsCommon/package.json
vNext/shared/AppInsightsCommon/src/Interfaces/Contracts/Generated/ContextTagKeys.ts
vNext/shared/AppInsightsCore/README.md
vNext/shared/AppInsightsCore/package.json

rename travis and github links to solve issues from org rename to microsoft.

docs: rename Microsoft to microsoft

---

vNext/shared/AppInsightsCommon/Tests/Selenium/appinsights-common.tests.ts
vNext/shared/AppInsightsCommon/Tests/Util.tests.ts
vNext/shared/AppInsightsCommon/src/Util.ts

Add fallback for parseUrl to fill the `host` field when `document.createElement` does not exist

common: add parseHost for fallback url parsing

---

vNext/AISKU/Tests/applicationinsights.e2e.tests.ts
vNext/AISKU/package-lock.json
vNext/AISKU/package.json
vNext/AISKU/src/Initialization.ts
vNext/AISKULight/package.json
vNext/channels/applicationinsights-channel-js/Tests/Sender.tests.ts
vNext/channels/applicationinsights-channel-js/package.json
vNext/channels/applicationinsights-channel-js/src/EnvelopeCreator.ts
vNext/channels/applicationinsights-channel-js/src/Sender.ts
vNext/common/config/rush/npm-shrinkwrap.json
vNext/extensions/applicationinsights-analytics-js/package.json
vNext/extensions/applicationinsights-analytics-js/src/JavaScriptSDK/ApplicationInsights.ts
vNext/extensions/applicationinsights-dependencies-js/package.json
vNext/extensions/applicationinsights-dependencies-js/src/ajax.ts
vNext/extensions/applicationinsights-properties-js/package.json
vNext/extensions/applicationinsights-properties-js/src/Context/Internal.ts
vNext/extensions/applicationinsights-properties-js/src/PropertiesPlugin.ts
vNext/extensions/applicationinsights-properties-js/src/TelemetryContext.ts
vNext/extensions/applicationinsights-react-js/package.json
vNext/extensions/applicationinsights-react-native/package.json
vNext/shared/AppInsightsCommon/package.json
vNext/shared/AppInsightsCommon/src/Interfaces/ITelemetryContext.ts
vNext/shared/AppInsightsCommon/src/Util.ts
vNext/shared/AppInsightsCommon/src/applicationinsights-common.ts
vNext/shared/AppInsightsCore/package.json

Addresses #857 
- Saves appId response from Breeze Channel in TelemetryContext instance. This is then used in the dependencies plugin when it grabs its context ref from properties plugin

save appId response from breeze channel in context

---

vNext/common/config/rush/npm-shrinkwrap.json
vNext/extensions/applicationinsights-react-js/package.json
vNext/extensions/applicationinsights-react-js/rollup.config.js

Addresses #891 
Modify rollup config to prevent react plugin from crashing users' Jest unit tests
- Adds commonjs rollup plugin
- Adds `preferBuiltins: true` to the node-resolve plugin
- Deletes browser rollup config, since the package.json does not reference a `browser` entry point

React (rollup): add commonjs plugin, preferBuiltins

---

README.md
vNext/AISKU/Tests/applicationinsights.e2e.tests.ts
vNext/AISKU/src/ApplicationInsightsDeprecated.ts
vNext/AISKU/src/Initialization.ts
vNext/extensions/applicationinsights-analytics-js/Tests/ApplicationInsights.tests.ts
vNext/extensions/applicationinsights-analytics-js/src/JavaScriptSDK/ApplicationInsights.ts
vNext/shared/AppInsightsCommon/src/Interfaces/IExceptionTelemetry.ts

Fixes https://github.com/microsoft/ApplicationInsights-node.js/issues/522
This PR aligns `trackException` API of this SDK with other App Insights SDKs. 
e.g [Node.js SDK](https://github.com/microsoft/ApplicationInsights-node.js/blob/develop/Declarations/Contracts/TelemetryTypes/ExceptionTelemetry.ts)
`appInsights.trackException({ exception: new Error() });`

rename IExceptionTelemetry.error to exception

---

vNext/AISKU/Tests/applicationinsights.e2e.tests.ts
vNext/channels/applicationinsights-channel-js/src/EnvelopeCreator.ts
vNext/extensions/applicationinsights-properties-js/Tests/Selenium/properties.tests.ts
vNext/extensions/applicationinsights-properties-js/src/Context/TelemetryTrace.ts

Adds previously existing behavior to automatically name a newly started operation.
V1 SDK:
https://github.com/microsoft/ApplicationInsights-JS/blob/a96b1a0e77a43e6ba64369cae635c678e009f4f8/JavaScript/JavaScriptSDK/Context/Operation.ts#L19-L23
Also saves the current operation id to each PageView.id as was done in V1 SDK.
https://github.com/microsoft/ApplicationInsights-JS/blob/a96b1a0e77a43e6ba64369cae635c678e009f4f8/JavaScript/JavaScriptSDK/AppInsights.ts#L140-L141

add operation.name, pageview.id

---

vNext/channels/applicationinsights-channel-js/src/Sender.ts

Add type checking to default constructor for `ISenderConfig`.
Adds missing `namePrefix` to default configuration for channel

add typechecking for ISenderConfig

---

vNext/extensions/applicationinsights-analytics-js/Tests/ApplicationInsights.tests.ts
vNext/extensions/applicationinsights-analytics-js/src/JavaScriptSDK/ApplicationInsights.ts

Remove redundant code. This functionality is currently performed by the breeze-channel and core. This change enables changing ikey in a telemetry initializer to also change `iKeyNoDashes` in `ITelemetryItem.name`.
https://github.com/microsoft/ApplicationInsights-JS/blob/96a5125a40229fb5c496a9a799d7deb26aa88b56/vNext/shared/AppInsightsCore/src/JavaScriptSDK/AppInsightsCore.ts#L164-L184
https://github.com/microsoft/ApplicationInsights-JS/blob/96a5125a40229fb5c496a9a799d7deb26aa88b56/vNext/channels/applicationinsights-channel-js/src/EnvelopeCreator.ts#L61-L65

analytics: remove ikey setter

---

vNext/AISKU/Tests/sanitizer.e2e.tests.ts
vNext/shared/AppInsightsCommon/src/Telemetry/RemoteDependencyData.ts

Adds missing string sanitization to `RDD.ts` that already exists in other Telemetry Classes.

common: sanitize rdd name and target

---

API.md
README.md

Docs incorrectly reference `resultCode`. Should be `responseCode`

docs: rename resultCode to responseCode

---

vNext/extensions/applicationinsights-analytics-js/src/JavaScriptSDK/ApplicationInsights.ts
vNext/extensions/applicationinsights-dependencies-js/src/ajax.ts
vNext/extensions/applicationinsights-properties-js/src/PropertiesPlugin.ts
vNext/extensions/applicationinsights-react-js/src/ReactPlugin.ts
vNext/extensions/applicationinsights-react-native/src/ReactNativePlugin.ts
vNext/shared/AppInsightsCore/package.json

Custom telemetry intializers are run in `processTelemetry` in the analytics plugin. It needs to be made as the last priority among the default plugins so that all other telemetry information from other plugins is available to custom telemetry initializers.
Also removes minified entry point from `core`

analytics: move to last priority of default plugins

---

README.md
vNext/extensions/applicationinsights-analytics-js/Tests/ApplicationInsights.tests.ts
vNext/extensions/applicationinsights-analytics-js/package.json
vNext/extensions/applicationinsights-analytics-js/src/JavaScriptSDK/ApplicationInsights.ts
vNext/shared/AppInsightsCommon/src/Interfaces/IConfig.ts

Adds new off-by-default configuration `enableAutoRouteTracking`, which listens for changes in the `window.history` stack to trigger a new pageview/operation. Each listener forwards events to the catch-all `locationchange` event to actually track the new pageview.
All events are prefixed with `config.namePrefix`, so that multiple instances of the SDK do not duplicate pageview telemetry to each instance.
README changes can be uncommented when the feature is shipped

Feature: add SPA auto route change tracking

---

README.md

README.md in root of repo had extra code fencing notes that caused the "Source Map Support" section to get treated as code and incorrectly rendered.

Fix rendering issue in readme

---

README.md

- Removed typo from documentation. `enable enable` -> `enable`

Fixed a typo. `enable enable` -> `enable`

---

vNext/extensions/applicationinsights-analytics-js/Tests/ApplicationInsights.tests.ts
vNext/extensions/applicationinsights-analytics-js/src/JavaScriptSDK/ApplicationInsights.ts

- Nulls out the referrer uri on route changes instead of using `document.referrer`, which never changes SPAs (#969)
- Adds a configurable offset, default 500ms, to wait until calling trackPageView to give time for `window.title` and other DOM elements to update (#967)
https://github.com/microsoft/ApplicationInsights-JS/compare/markwolff/spa-route-changes?expand=1#diff-3a1cf06b58810f39d62ba7f728e6e3c7R612 (Related to #804)

route tracking: track pageview after delay

---

vNext/extensions/applicationinsights-analytics-js/Tests/ApplicationInsights.tests.ts
vNext/extensions/applicationinsights-analytics-js/src/JavaScriptSDK/ApplicationInsights.ts
vNext/shared/AppInsightsCommon/Tests/Util.tests.ts
vNext/shared/AppInsightsCommon/src/Util.ts

Fixes #998 
Adds analytics plugin polyfill for `new Event` so that it can be run in Ie

routes: add ie polyfill for Event constructor

---

vNext/channels/applicationinsights-channel-js/Tests/Sender.tests.ts
vNext/channels/applicationinsights-channel-js/src/EnvelopeCreator.ts
vNext/shared/AppInsightsCommon/src/Telemetry/RemoteDependencyData.ts

Parse currently unused `dependency.correlationContext` field and appends its value to `dependency.target` when envelope is constructed.
- Fixes #1019

fix(rdd): parse correlationContext, if present

---

vNext/shared/AppInsightsCore/src/JavaScriptSDK.Interfaces/IAppInsightsCore.ts
vNext/shared/AppInsightsCore/src/JavaScriptSDK/AppInsightsCore.ts

update this function interface so 1P can pass in a eventName to update the name filed of an item of MessageData type.

udpate pollInternalLogs method of core

---

vNext/extensions/applicationinsights-analytics-js/src/JavaScriptSDK/ApplicationInsights.ts

Add missing nullchecks to new `window.location` uses.
Fixes #1027

fix(analytics): add nullcheck to window

---

vNext/AISKU/Tests/TelemetryValidation/CommonValidator.ts
vNext/AISKU/Tests/TelemetryValidation/ExceptionValidator.ts
vNext/AISKU/Tests/applicationinsights.e2e.tests.ts
vNext/extensions/applicationinsights-analytics-js/Tests/ApplicationInsights.tests.ts
vNext/extensions/applicationinsights-dependencies-js/src/TraceParent.ts
vNext/shared/AppInsightsCommon/Tests/Exception.tests.ts
vNext/shared/AppInsightsCommon/src/Interfaces/IExceptionTelemetry.ts
vNext/shared/AppInsightsCommon/src/Telemetry/Exception.ts

When used with app insights channel, SDK will convert `exception.ver: string = "4.0"` to `exception.ver: number = 2`. Currently it just force casts it between 4.0 and 2.0 since these are the only versions we care about. On updates to CS4.1, 5.0, etc these tests will fail as an alert.
/cc @hectorhdzg

fix: force ver casting btwn cs 4.0 and cs 2.0

---

extensions/applicationinsights-react-native/Tests/tsconfig.json
extensions/applicationinsights-react-native/package.json
extensions/applicationinsights-react-native/src/ReactNativePlugin.ts
extensions/applicationinsights-react-native/tsconfig.json
gruntfile.js

Update RN plugin to use latest [device info version](https://github.com/react-native-community/react-native-device-info/wiki/V3-to-V4-Migration-Guide).

chore: bump to use latest RNDI package

---

legacy/JavaScript/JavaScriptSDK/Util.ts

Legacy clone of appending `;SameSite=None` to new `ai_user`, `ai_session` cookies

add samesite=none to legacy cookies

---

AISKU/README.md
README.md
legacy/README.md

Adds "static initialization" setup instructions which existed on the legacy version of the SDK.

docs: Add new setup method

---

extensions/applicationinsights-analytics-js/src/JavaScriptSDK/ApplicationInsights.ts
shared/AppInsightsCommon/src/Interfaces/IConfig.ts

- New global handled for unhandledrejection, similar to onerror
- New config property to test for
Addresses #1013
Replaced #1069

Added support for logging unhandled promise rejections

---

extensions/applicationinsights-analytics-js/src/JavaScriptSDK/ApplicationInsights.ts

User can specify telemetryInitializers before calling initialize we are currently deleting them, initialize can be only called once so there is not issue with adding duplicated default telemetryInitializers

Do not clean telemetryInitializers during initialization

---

AISKU/Tests/applicationinsights.e2e.tests.ts
README.md
extensions/applicationinsights-dependencies-js/Tests/Selenium/ajax.tests.ts
extensions/applicationinsights-dependencies-js/src/ajax.ts
shared/AppInsightsCommon/src/Interfaces/IConfig.ts
shared/AppInsightsCommon/src/Interfaces/ICorrelationConfig.ts

Include response error data in part C on dependency event when ajax respond code is not 200.
Closes: #1156

include response error data

---

extensions/applicationinsights-properties-js/src/TelemetryContext.ts
shared/AppInsightsCommon/src/Util.ts

add null check for sessionManager

---

common/config/rush/npm-shrinkwrap.json
legacy/JavaScript/JavaScriptSDK.Tests/CheckinTests/Util.tests.ts
legacy/JavaScript/JavaScriptSDK/Util.ts

Address UA validation when setting SameSite attribute on the cookie for the Legacy build

Legacy Manage SameSite Cookie Settings #1126

---

AISKU/src/Init.ts
legacy/JavaScript/JavaScriptSDK/ajax/ajax.ts
shared/AppInsightsCommon/src/Util.ts
shared/AppInsightsCore/src/JavaScriptSDK/ProcessTelemetryContext.ts

Address issue #1173 where the declaration of the methods does not match the actual implementation.

[BUG] Typescript build with 2.4.0 breaks #1173

---

extensions/applicationinsights-analytics-js/Tests/ApplicationInsights.tests.ts
extensions/applicationinsights-analytics-js/src/JavaScriptSDK/ApplicationInsights.ts

Add `properties` param for `stopTrackPage` function to capture part c customProperties.
Closes #1189

stopTrackPage missing part c properties

---

API-reference.md

I removed the description for pageTags (under IPageViewTelemetry) in 
API-reference.md because it doesn't exist in the code or released 
product anymore.

API Reference doc updated

---

AISKU/src/Initialization.ts
extensions/applicationinsights-properties-js/src/Context/Internal.ts
extensions/applicationinsights-properties-js/src/TelemetryContext.ts
shared/AppInsightsCommon/src/Interfaces/Contracts/Generated/ContextTagKeys.ts

Identify whether the script is being consumed via the CDN or NPM package

---

channels/applicationinsights-channel-js/src/Sender.ts
extensions/applicationinsights-dependencies-js/src/ajax.ts
shared/AppInsightsCommon/Tests/Util.tests.ts
shared/AppInsightsCommon/src/Util.ts
shared/AppInsightsCore/src/JavaScriptSDK/CoreUtils.ts
tools/rollup-es3/src/es3/Es3Tokens.ts
tools/rollup-es3/src/es3/Interfaces.ts
tools/rollup-es3/src/es3/Utils.ts

[BUG] ajax.ts is using string trim() which is not supported on IE7/8 #1251

[BUG] Can't include Correlation Header on IE can fail #1260

---

extensions/applicationinsights-react-js/src/withAITracking.tsx

fix for issues #1274 and #1117
Can also use empty string instead of 'Anonymous component'. Let me know which is preferred.

fix for withAITracking wrapping functional components.

---

AISKULight/index.ts
channels/applicationinsights-channel-js/Tests/Sender.tests.ts
channels/applicationinsights-channel-js/src/Sender.ts
common/config/rush/npm-shrinkwrap.json
shared/AppInsightsCore/src/JavaScriptSDK.Enums/LoggingEnums.ts
shared/AppInsightsCore/src/JavaScriptSDK.Enums/SendRequestReason.ts
shared/AppInsightsCore/src/JavaScriptSDK.Interfaces/INotificationListener.ts
shared/AppInsightsCore/src/JavaScriptSDK.Interfaces/INotificationManager.ts
shared/AppInsightsCore/src/JavaScriptSDK/BaseCore.ts
shared/AppInsightsCore/src/JavaScriptSDK/NotificationManager.ts
shared/AppInsightsCore/src/applicationinsights-core-js.ts

Adds a notification for when events are about to be sent to the server

Add Send Request notification

---

AISKU/package.json
AISKULight/package.json
RELEASES.md
channels/applicationinsights-channel-js/Tests/Sender.tests.ts
channels/applicationinsights-channel-js/package.json
channels/applicationinsights-channel-js/src/EnvelopeCreator.ts
common/config/rush/npm-shrinkwrap.json
extensions/applicationinsights-analytics-js/package.json
extensions/applicationinsights-analytics-js/src/JavaScriptSDK/ApplicationInsights.ts
extensions/applicationinsights-angular-js/package.json
extensions/applicationinsights-dependencies-js/package.json
extensions/applicationinsights-properties-js/package.json
extensions/applicationinsights-properties-js/src/Context/Internal.ts
extensions/applicationinsights-react-js/package.json
extensions/applicationinsights-react-native/package.json
shared/AppInsightsCommon/package.json
shared/AppInsightsCore/package.json

- #1278 Add optional 'eventsSendRequest' notification to NotificationManager
- #1269 TsLib v1.13.0 has breaking change (Remove dependency on TSLib)
- Added new package **'applicationinsights-shims@1.0.0'**
- #991 Don't work with React HOOKS
- #1120 Introducing React Hooks for AppInsights #1120
- #1274 Fix for withAITracking wrapping functional components.
- Using crypto to generate GUIDs when available (Make GUID more random)
- #1260 [BUG] Can't include Correlation Header on IE can fail
- #1258 Update snippet to support reporting script load failures
- #1251 [BUG] ajax.ts is using string trim() which is not supported on IE7/8
- #1249 Identify whether the script is being consumed via the CDN or NPM package
- Several minor documentation updates
- Created to remove dependency on TSLib as v …

[Release] Increase to version 2.5.5

---

AISKU/snippet/snippet.js

This fixes #1283.
This PR ensures AppInsights stub methods use the correct method names when tracking method calls before JS dependency has been downloaded.

Fix incorrect closure in _createMethods in snippet.js

---

legacy/JavaScript/JavaScriptSDK/Context/Operation.ts
legacy/JavaScript/JavaScriptSDK/Util.ts

- Use longer w3c id for legacy operation id's to prevent conflicting op ids. If no conflicts occur, viewing app insights data on the Portal can use the new Indexer feature for significantly improved blade load times.

legacy: use w3c id for new operations

---

extensions/applicationinsights-angularplugin-js/README.md
extensions/applicationinsights-angularplugin-js/Tests/test-app/src/app/Channel.ts
extensions/applicationinsights-angularplugin-js/Tests/test-app/src/app/Common.ts
extensions/applicationinsights-angularplugin-js/Tests/test-app/src/app/TestComponent.ts
extensions/applicationinsights-angularplugin-js/Tests/test-app/src/app/app.component.spec.ts
extensions/applicationinsights-angularplugin-js/rollup.config.js
extensions/applicationinsights-angularplugin-js/src/AngularPluginService.ts
extensions/applicationinsights-angularplugin-js/src/applicationinsights-angularplugin-js.ts

This PR adds trackMetric method for Angular plugin to allow users to track component usage (component existed time in seconds). 
- call trackMetric inside component life cycle hook method `ngOnDestroy` to trigger sending a metric event with component existed time, with an additional property component name.
- one example metric event:

Add trackMetric method for Angular plugin

---

shared/AppInsightsCore/src/JavaScriptSDK/BaseCore.ts

Logger is not available before initialization causing issues with inherited classes Ex: JSLL shim.

Adding logger during core constructor

---

extensions/applicationinsights-clickanalytics-js/README.md

Changes in configuration
Removed Snippet based setup. (not valid for click plugin)

Click Plugin Docs Updates

---

AISKU/package.json
AISKULight/package.json
channels/applicationinsights-channel-js/package.json
common/Tests/Framework/package.json
common/config/rush/npm-shrinkwrap.json
common/scripts/install-run-rush.js
common/scripts/install-run.js
extensions/applicationinsights-analytics-js/package.json
extensions/applicationinsights-clickanalytics-js/package.json
extensions/applicationinsights-debugplugin-js/package.json
extensions/applicationinsights-dependencies-js/package.json
extensions/applicationinsights-properties-js/package.json
extensions/applicationinsights-react-js/package.json
extensions/applicationinsights-react-native/package.json
package.json
rush.json
shared/AppInsightsCommon/package.json
shared/AppInsightsCore/package.json

Update React/ReactNative base package version
Update Rush version

Update DynamicProto version

---

extensions/applicationinsights-react-js/package.json
extensions/applicationinsights-react-native/package.json

- Remove prepublishOnly script as it's already packed during build validation

[Release][React] Release Fix for v3.1.2

---

.github/workflows/stale.yml

- Starting with high values because we have not had this before
- Initial values should be 300 days => stale and 30 days => close

Add Stale Issue / PR GitHub Action

---

common/config/rush/npm-shrinkwrap.json
extensions/applicationinsights-properties-js/src/Context/User.ts
extensions/applicationinsights-properties-js/src/PropertiesPlugin.ts
shared/AppInsightsCommon/src/Interfaces/Context/IUser.ts
shared/AppInsightsCore/src/JavaScriptSDK.Interfaces/ICookieMgr.ts
shared/AppInsightsCore/src/JavaScriptSDK/CookieMgr.ts

- Add optimization to avoid always updating the cookie value

ai_user cookie not present after reenabling the cookie #1585

---

AISKU/Tests/AISKUSize.Tests.ts
AISKU/Tests/Selenium/appinsights-sdk.tests.ts
AISKU/Tests/applicationinsights.e2e.fetch.tests.ts
AISKU/Tests/applicationinsights.e2e.tests.ts
README.md
channels/applicationinsights-channel-js/Tests/Unit/src/Sender.tests.ts
channels/applicationinsights-channel-js/src/EnvelopeCreator.ts
channels/applicationinsights-channel-js/src/Interfaces.ts
channels/applicationinsights-channel-js/src/Offline.ts
channels/applicationinsights-channel-js/src/SendBuffer.ts
channels/applicationinsights-channel-js/src/Sender.ts
channels/applicationinsights-channel-js/src/TelemetryProcessors/Sample.ts
channels/applicationinsights-channel-js/src/TelemetryProcessors/SamplingScoreGenerators/HashCodeScoreGenerator.ts
channels/applicationinsights-channel-js/src/TelemetryProcessors/SamplingScoreGenerators/SamplingScoreGenerator.ts
extensions/applicationinsights-clickanalytics-js/src/handlers/AutoCaptureHandler.ts
extensions/applicationinsights-dependencies-js/src/ajax.ts
extensions/applicationinsights-dependencies-js/src/ajaxUtils.ts
shared/AppInsightsCommon/src/HelperFuncs.ts
shared/AppInsightsCommon/src/Interfaces/Context/ISample.ts
shared/AppInsightsCommon/src/Interfaces/IConfig.ts
shared/AppInsightsCommon/src/Util.ts
shared/AppInsightsCommon/src/applicationinsights-common.ts
shared/AppInsightsCore/src/JavaScriptSDK/CoreUtils.ts
shared/AppInsightsCore/src/JavaScriptSDK/EnvUtils.ts
shared/AppInsightsCore/src/applicationinsights-core-js.ts

- Use fetch with keepalive support during unload by default (Main CORB fix)
- Fix fetch usage to stop tracking the track call
- Minification and minor performance improvements

Some requests are returning a CORB error for responses containing text content type #1683

---

AISKU/Tests/Perf/src/AISKUPerf.ts
AISKU/package.json
AISKULight/package.json
RELEASES.md
channels/applicationinsights-channel-js/Tests/Unit/src/Sender.tests.ts
channels/applicationinsights-channel-js/package.json
channels/applicationinsights-channel-js/src/EnvelopeCreator.ts
common/config/rush/npm-shrinkwrap.json
extensions/applicationinsights-analytics-js/package.json
extensions/applicationinsights-analytics-js/src/JavaScriptSDK/ApplicationInsights.ts
extensions/applicationinsights-clickanalytics-js/package.json
extensions/applicationinsights-clickanalytics-js/src/ClickAnalyticsPlugin.ts
extensions/applicationinsights-debugplugin-js/package.json
extensions/applicationinsights-dependencies-js/package.json
extensions/applicationinsights-perfmarkmeasure-js/package.json
extensions/applicationinsights-properties-js/package.json
extensions/applicationinsights-properties-js/src/Context/Internal.ts
extensions/applicationinsights-react-js/package.json
extensions/applicationinsights-react-native/package.json
package.json
shared/AppInsightsCommon/package.json
shared/AppInsightsCore/package.json
tools/chrome-debug-extension/manifest.json
tools/chrome-debug-extension/package.json
version.json

- React-js to 3.2.2
- ReactNative to 2.4.2
- ChromeExt to 0.2.2

[Release] Increase version to 2.7.2

---

tools/release-tools/setVersion.js
version.json

Update version update script to support default "next" release version (major/minor) not just patch (https://github.com/microsoft/ApplicationInsights-JS/pull/1756)

Merge [master] to [beta]

---

.github/workflows/ci.yml
.github/workflows/codeql-analysis.yml
common/Tests/Framework/src/Assert.ts
common/Tests/Framework/src/DebugHelpers.ts
shared/AppInsightsCore/Tests/Perf/src/CorePerfCheck.Tests.ts
shared/AppInsightsCore/Tests/Unit/src/ApplicationInsightsCore.Tests.ts
shared/AppInsightsCore/Tests/Unit/src/HelperFunc.Tests.ts
shared/AppInsightsCore/src/JavaScriptSDK/HelperFuncs.ts
shared/AppInsightsCore/src/JavaScriptSDK/InstrumentHooks.ts
tools/release-tools/setVersion.js
version.json

This is performing a rebase/merge from [master] to [beta]

Merge [master] branch to [beta] and Enable GitHub Actions on [beta] branch

---

shared/AppInsightsCore/Tests/Unit/src/Dynamic.Tests.ts
shared/AppInsightsCore/src/JavaScriptSDK.Enums/SendRequestReason.ts
shared/AppInsightsCore/src/JavaScriptSDK.Enums/TelemetryUnloadReason.ts
shared/AppInsightsCore/src/JavaScriptSDK.Interfaces/IAppInsightsCore.ts
shared/AppInsightsCore/src/JavaScriptSDK/BaseCore.ts
shared/AppInsightsCore/src/JavaScriptSDK/BaseTelemetryPlugin.ts
shared/AppInsightsCore/src/JavaScriptSDK/HelperFuncs.ts
shared/AppInsightsCore/src/JavaScriptSDK/ProcessTelemetryContext.ts
shared/AppInsightsCore/src/JavaScriptSDK/UnloadHandlerContainer.ts
shared/AppInsightsCore/src/applicationinsights-core-js.ts

Beta Part 3: Part of Mega Dynamic Load/Unload support

---

common/config/rush/npm-shrinkwrap.json
shared/AppInsightsCore/src/JavaScriptSDK.Enums/EnumHelperFuncs.ts
tools/chrome-debug-extension/src/telemetryViewerPopup.tsx

- [BUG] Angular project doesn't build after install latest version v.2.8.0 #1807

v2.8.0 has incompatible TypeScript 3.x type declaration

---

extensions/applicationinsights-react-js/src/applicationinsights-react-js.ts
extensions/applicationinsights-react-js/src/withAITracking.tsx

While withAITracking function is working in most of the cases, it's not useful in a scenario when a content of the wrapped component is not physically located under the component's DOM tree. 
An example of that is Modal component from Microsoft Fluent UI framework but there are many other similar cases too.
Therefore, a developer may sometimes need to create a custom version of the HOC function, which for example, as in the case of the Modal component would wrap a content instead of the component itself, however still have the same tracking functionality as the app insights library HOC function.
The change here extract the HOC class so it can be re-used and customized by consumers of the library

Extracting HOC tracked component class base for re-use

---

extensions/applicationinsights-react-js/src/AppInsightsErrorBoundary.tsx

Closes  https://github.com/microsoft/ApplicationInsights-JS/issues/1804

fix: add children prop to error boundary props

---

shared/AppInsightsCore/Tests/Unit/src/W3cTraceParentTests.ts
shared/AppInsightsCore/src/JavaScriptSDK/CoreUtils.ts

[BUG] Performance improvements when calling newGuid multiple times (like 10,000) #1870

[BUG] Performance improvements when calling newGuid multiple times

---

extensions/applicationinsights-clickanalytics-js/Tests/Unit/src/ClickEventTest.ts
extensions/applicationinsights-clickanalytics-js/src/DataCollector.ts
extensions/applicationinsights-clickanalytics-js/src/Interfaces/Datamodel.ts

Details on this issue: https://github.com/microsoft/ApplicationInsights-JS/issues/1863
`urlCollectQuery` and `urlCollectHash` configs are removed in this PR: https://github.com/microsoft/ApplicationInsights-JS/pull/1444
and the changes on Readme are back in PR: https://github.com/microsoft/ApplicationInsights-JS/pull/1455 due to auto merge

Add clickanalytics plugin url config back

---

channels/applicationinsights-channel-js/src/Sender.ts
common/config/rush/npm-shrinkwrap.json

[Task 15215355]: [Breeze] Update retry error handling on breeze for returned 500 errors

[JS SDK] Update Retry logic to handle additional response codes

---

AISKU/Tests/Unit/src/AISKUSize.Tests.ts
AISKU/Tests/Unit/src/CdnPackaging.tests.ts

[Beta] Update size tests to automatically use the major number from the current version (#1873)
- this is automatically updated by the version scripts

Cherry-Picking beta fix so merging master -> beta stops breaking nightly beta release

---

README.md

The file linked in the 'Changelist' had been deprecated, moved to https://github.com/microsoft/ApplicationInsights-JS/releases , an active and dynamically supported list of releases.

Fixed release notes, previously used a deprecated file.

---

gruntfile.js
shared/AppInsightsCore/Tests/Perf/src/CorePerfCheck.Tests.ts

And bump the time for tests that are failing on the virtualized nightly perf runs

Update PerfTests to use the latest version

---

AISKULight/Tests/Unit/src/AISKULightSize.Tests.ts

The Nightly deployment is failure because the "version" string included contains "nightly" which just pushes the compressed size of AISKU Lite now.

Fix size check which "nightly" is added to the bundle

---

common/config/rush/npm-shrinkwrap.json
extensions/applicationinsights-properties-js/Tests/Unit/src/SessionManager.Tests.ts
extensions/applicationinsights-properties-js/Tests/Unit/src/properties.tests.ts
extensions/applicationinsights-properties-js/src/Context/Internal.ts
extensions/applicationinsights-properties-js/src/Context/Session.ts
extensions/applicationinsights-properties-js/src/Context/User.ts
extensions/applicationinsights-properties-js/src/Interfaces/IPropertiesConfig.ts
extensions/applicationinsights-properties-js/src/PropertiesPlugin.ts
extensions/applicationinsights-properties-js/src/TelemetryContext.ts
shared/AppInsightsCore/Tests/Unit/src/DynamicConfig.Tests.ts
shared/AppInsightsCore/src/Config/DynamicConfig.ts
shared/AppInsightsCore/src/Config/DynamicProperty.ts
shared/AppInsightsCore/src/Config/DynamicState.ts
shared/AppInsightsCore/src/Config/IDynamicConfigHandler.ts
shared/AppInsightsCore/src/Config/IDynamicWatcher.ts
shared/AppInsightsCore/src/Config/_IDynamicConfigHandlerState.ts
shared/AppInsightsCore/src/JavaScriptSDK/AppInsightsCore.ts
shared/AppInsightsCore/src/JavaScriptSDK/BaseTelemetryPlugin.ts
shared/AppInsightsCore/src/JavaScriptSDK/ProcessTelemetryContext.ts
shared/AppInsightsCore/src/JavaScriptSDK/UnloadHandlerContainer.ts
shared/AppInsightsCore/src/JavaScriptSDK/UnloadHookContainer.ts
shared/AppInsightsCore/src/applicationinsights-core-js.ts

- Add ability to tag Dynamic Config properties as referenced to support updating extensionConfig in-place with a new object instance
- Add IUnloadHookContainer to allow passing extension level unload hook container to sub-components

Followup for [Beta][Task]15982357: Dynamic config for Properties extension #1972

---

common/config/rush/npm-shrinkwrap.json
shared/AppInsightsCommon/Tests/Unit/src/ThrottleMgr.tests.ts
shared/AppInsightsCommon/src/Interfaces/IThrottleMgr.ts
shared/AppInsightsCommon/src/ThrottleMgr.ts

https://github.com/microsoft/ApplicationInsights-JS/issues/1979

[AI][Task]16961420: fix throttleMgr incorrectly fires based on the number of days past

---

AISKU/API.md
API-reference.md
README.md
docs/SdkLoadFailureSteps.md
extensions/applicationinsights-clickanalytics-js/README.md
extensions/applicationinsights-perfmarkmeasure-js/README.md

change instrumentation key to connection string

change readme

---

AISKULight/README.md
README.md
extensions/applicationinsights-dependencies-js/src/ajaxRecord.ts

Documentation updates to address #1794 and #1792

---

channels/applicationinsights-channel-js/src/Sender.ts
channels/tee-channel-js/src/TeeChannel.ts
examples/shared-worker/package.json
extensions/applicationinsights-analytics-js/src/JavaScriptSDK/AnalyticsPlugin.ts
extensions/applicationinsights-analytics-js/src/JavaScriptSDK/Telemetry/PageVisitTimeManager.ts
extensions/applicationinsights-clickanalytics-js/src/ClickAnalyticsPlugin.ts
extensions/applicationinsights-properties-js/src/Context/User.ts
extensions/applicationinsights-properties-js/src/PropertiesPlugin.ts
shared/AppInsightsCommon/src/Interfaces/IChannelControlsAI.ts
shared/AppInsightsCommon/src/applicationinsights-common.ts
shared/AppInsightsCore/Tests/Unit/src/Dynamic.Tests.ts
shared/AppInsightsCore/Tests/Unit/src/DynamicConfig.Tests.ts
shared/AppInsightsCore/Tests/Unit/src/EventHelper.Tests.ts
shared/AppInsightsCore/Tests/Unit/src/TestPlugins.ts
shared/AppInsightsCore/Tests/Unit/src/UpdateConfig.Tests.ts
shared/AppInsightsCore/src/Config/DynamicConfig.ts
shared/AppInsightsCore/src/Config/DynamicProperty.ts
shared/AppInsightsCore/src/JavaScriptSDK.Interfaces/IChannelControlsHost.ts
shared/AppInsightsCore/src/JavaScriptSDK.Interfaces/IConfiguration.ts
shared/AppInsightsCore/src/JavaScriptSDK.Interfaces/ITelemetryPlugin.ts
shared/AppInsightsCore/src/JavaScriptSDK/AppInsightsCore.ts
shared/AppInsightsCore/src/JavaScriptSDK/DataCacheHelper.ts
shared/AppInsightsCore/src/JavaScriptSDK/HelperFuncs.ts
shared/AppInsightsCore/src/JavaScriptSDK/PerfManager.ts
shared/AppInsightsCore/src/applicationinsights-core-js.ts

- Bug fixes for getPlugin() not searching the TeeChannel
- Minification improcements

[Main] Fix extension / channel not being readonly

---

AISKU/package.json
AISKULight/package.json
channels/applicationinsights-channel-js/package.json
common/config/rush/command-line.json
extensions/applicationinsights-analytics-js/package.json
extensions/applicationinsights-clickanalytics-js/package.json
extensions/applicationinsights-debugplugin-js/package.json
extensions/applicationinsights-dependencies-js/package.json
extensions/applicationinsights-perfmarkmeasure-js/package.json
extensions/applicationinsights-properties-js/package.json
package.json
shared/AppInsightsCommon/package.json
shared/AppInsightsCore/package.json
tools/applicationinsights-web-snippet/package.json
tools/release-tools/npm_publish.js
tools/release-tools/package_groups.json
tools/rollup-es3/package.json
tools/shims/package.json

Update is needed as the dev-ops npm authentication does not propagate to different rush package calls.

[Master] Update NPM publish scripts

---

extensions/applicationinsights-dependencies-js/Tests/Unit/src/ajax.tests.ts
extensions/applicationinsights-dependencies-js/src/ajax.ts

This allows AI to track the dependency and sets the Traceparent header on the request to the server (if otherwise allowed).
`Traceparent` is now set
Fully-populated dependency is sent to ApplicationInsights
Data is displayed in Application Insights
Fixes #2164

[main] use proper URL for tracking when fetch is passed an empty string

---

shared/AppInsightsCommon/src/ConnectionStringParser.ts
tools/applicationinsights-web-snippet/src/snippet.ts

[main] remove double slash for endPointUrl

---

extensions/applicationinsights-analytics-js/src/JavaScriptSDK/AnalyticsPlugin.ts
extensions/applicationinsights-analytics-js/src/JavaScriptSDK/Telemetry/PageViewManager.ts
shared/AppInsightsCommon/src/Interfaces/IPageViewPerformanceTelemetry.ts
shared/AppInsightsCommon/src/Interfaces/IPageViewTelemetry.ts

only modify the startTime for first page view telemetry

[main] fix startTime timestamp

---

extensions/applicationinsights-properties-js/Tests/Unit/src/properties.tests.ts
extensions/applicationinsights-properties-js/src/PropertiesPlugin.ts

related to pr #2196 and issue #2028

[Main] v3.1.x change Disable UserAgent config to true by default #2028

---

tools/status-tools/github-status.js

Add a -dump flag to report which issues where open, closed and label etc for easier identifying of the issues for the month

Update GitHub Status script

---

README.md

based on local experiment, 
appInsights.stopTrackEvent("test",{property: {p1:3, p2:4}}) 
appInsights.stopTrackEvent("test3", {prop1: 1, prop2: "string", prop3: 4});
appInsights.stopTrackEvent("test4", {prop1: 1, prop2: "string", prop3: {t:"k"}}); appInsights.stopTrackPage("testtest","url", {"a":"apple", b:3})
appInsights.stopTrackPage("test9","url", {"a":"apple", b:"TEST"})
could all work, and the properties are shown in azure portal

[main] Add example of how to use stopTrackEvent #2209

---

AISKU/src/AISku.ts
README.md
shared/AppInsightsCommon/src/Interfaces/IAppInsights.ts

[main] correct types define for stopTrackEvent and stopTrackPage for #2209

---

AISKU/package.json
AISKULight/package.json
channels/1ds-post-js/package.json
channels/applicationinsights-channel-js/package.json
channels/offline-channel-js/package.json
channels/tee-channel-js/package.json
common/Tests/Framework/package.json
examples/AISKU/package.json
examples/cfgSync/package.json
examples/dependency/package.json
examples/shared-worker/package.json
extensions/applicationinsights-analytics-js/package.json
extensions/applicationinsights-cfgsync-js/package.json
extensions/applicationinsights-clickanalytics-js/package.json
extensions/applicationinsights-debugplugin-js/package.json
extensions/applicationinsights-dependencies-js/package.json
extensions/applicationinsights-osplugin-js/package.json
extensions/applicationinsights-perfmarkmeasure-js/package.json
extensions/applicationinsights-properties-js/package.json
shared/1ds-core-js/package.json
shared/AppInsightsCommon/package.json
shared/AppInsightsCore/package.json
shared/AppInsightsCore/src/JavaScriptSDK/DataCacheHelper.ts
tools/chrome-debug-extension/package.json
tools/shims/package.json

Reset the version number for DataCacheHelper

---

AISKU/src/Init.ts
tools/applicationinsights-web-snippet/src/snippet.ts

related to issue #2355 
tests locally and works using the new script as following:
<script type="text/javascript" >
!(function (cfg)......
src: "http://localhost:9001/AISKU/browser/es5/ai.3.2.1.js",
name: "appInsights2", // Global SDK Instance name defaults to "appInsights" when not supplied
});
</script>

[main] set script attribut to avoid race condition when multiple sdks are inited #2355

---

channels/offline-channel-js/src/Helpers/Utils.ts
channels/offline-channel-js/src/Interfaces/IOfflineBatch.ts
channels/offline-channel-js/src/Interfaces/IOfflineProvider.ts
examples/dependency/src/appinsights-init.ts
examples/dependency/src/dependencies-example-index.ts
examples/dependency/src/utils.ts
extensions/applicationinsights-dependencies-js/Tests/Unit/src/ajax.tests.ts
extensions/applicationinsights-dependencies-js/src/ajax.ts
shared/AppInsightsCommon/src/Interfaces/ICorrelationConfig.ts

this one is to avoid dealing with instrumentation key that may be a promise type #2340

[main] update the way to generate ajax perforamance mark prefix

---

.gitignore
AISKU/Tests/es6-module-type-check/package.json
AISKU/package.json
AISKULight/package.json
channels/applicationinsights-channel-js/package.json
channels/offline-channel-js/package.json
channels/tee-channel-js/package.json
common/Tests/Framework/package.json
common/config/rush/npm-shrinkwrap.json
examples/AISKU/package.json
examples/cfgSync/package.json
examples/dependency/package.json
examples/shared-worker/package.json
extensions/applicationinsights-analytics-js/package.json
extensions/applicationinsights-cfgsync-js/package.json
extensions/applicationinsights-clickanalytics-js/package.json
extensions/applicationinsights-debugplugin-js/package.json
extensions/applicationinsights-dependencies-js/package.json
extensions/applicationinsights-perfmarkmeasure-js/package.json
extensions/applicationinsights-properties-js/package.json
shared/AppInsightsCommon/package.json
shared/AppInsightsCore/package.json
tools/rollup-es5/package.json
tools/rollup-plugin-uglify3-js/package.json

- Changing from `*` as not all package managers handle this correctly
- This is an interim "fix", as at some point we indend to remove this from peerDependency completely, however, that requires more testing than this change to ensure no-one would be broken.

[Main] Change tslib peerDependency from "*" to open range

---

shared/AppInsightsCore/src/JavaScriptSDK.Interfaces/IExceptionConfig.ts

related to pr: https://github.com/microsoft/ApplicationInsights-JS/pull/2391

[main] fix expCfg to be optional

---

AISKU/src/AISku.ts
shared/AppInsightsCore/src/JavaScriptSDK/AppInsightsCore.ts

- Additional Minification improvements

[main] Minor fixes for handling ikey promises with dynamic changes

---

extensions/applicationinsights-dependencies-js/src/DependencyListener.ts
extensions/applicationinsights-dependencies-js/src/ajax.ts

I want to add the possibility to drop the enrichment of the correlation header using the dependencyListenerFunction like it is done for the dependencyInitializerFunction. In this way we can drop events that are not relevant for the current instance of the SDK especially in case of multiple instances with microservices.
This resolves #2505

Drop correlation header to be passed on the dependency

---

shared/AppInsightsCore/src/Config/ConfigDefaults.ts

We've encountered an issue where a customer had monkey patched Arrays to have a `set` method (as well as a few more methods) and this caused issues with the default config values, as `_isConfigDefaults` returned `true` instead of `false` for array values. We could also move it to only invalidate the `set` branch, but this fix felt safe enough to me.
Hopefully this fix is acceptable.

add negative isArray check to _isConfigDefaults

---

extensions/applicationinsights-clickanalytics-js/src/handlers/AutoCaptureHandler.ts

Changes made in https://github.com/microsoft/ApplicationInsights-JS/pull/2504 (b5a24d524bc0cae3c48c7010d88cef5f982449c8) appear to have introduced an issue when evaluating if events have come from known HTML objects. This appears to be due to a new array which had previously been an object still being indexed by its values. As a result these events are not being processed.
This change is to fix that by looking for the value in the array.

Click Analytics - Fix capturning of HTML events
